openapi: "3.0.0"
info:
  title: Databack Cloud API
  description: API for communications and administration of databacker instances
  version: "1.0.0"
paths: {} # technically not needed under openapi3, but does not hurt, and aids backwards-compatibility
components:
  schemas:
    Metadata:
      type: object
      properties:
        name:
          type: string
          description: name of the config
        description:
          type: string
          description: description of the config
        digest:
          type: string
          description: SHA256 digest of the config, optional

    NewInstance:
      type: object
      description: information for a new licensed databacker instance
      properties:
        publicKey:
          type: string
          description: ECDSA public key to associate with the instance, PEM-encoded
    InstanceBody:
      type: object
      properties:
        id:
          type: string
          example: 550e8400-e29b-41d4-a716-446655440000

    Log:
      type: object
      properties:
        run:
          type: string
          example: 550e8400-e29b-41d4-a716-446655440000
          description: run ID as UUID
        timestamp:
          type: string
          description: timestamp for the date and time of a message, in RFC3339 format
        level:
          type: string
          description: log level of the message, one of debug, info, warn, error, fatal
        fields:
          type: object
          additionalProperties: true
          description: key-value pairs for descriptive fields for the log message
        message:
          type: string
          description: actual message

    LogSummary:
      type: object
      properties:
        id:
          type: string
          example: 550e8400-e29b-41d4-a716-446655440000
        date:
          type: integer
          description: timestamp for start of backup run
        completion:
          type: integer
          description: completion code, using a subset of http codes
        size:
          type: integer
          description: size of logs in bytes

  securitySchemes:
    # note that we could explicitly use the "type: oauth2" with flows, but that would
    # require stating the endpoints, which are an implementation detail, and would not
    # let us restrict it to JWT, as oauth does not declare the token format.
    # The endpoints and how the JWT bearer token is retrieved should be an implementation detail.
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
