/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/system/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description health check endpoint, accessible without authentication */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description system is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description register a new user; does not require a pre-existing user record, only a valid JWT from the identity provider */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description information for the new user */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserWithEmail"];
                };
            };
            responses: {
                /** @description successfully registered user */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ID"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description User already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve the profile of the calling user, scoped to the JWT subject */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description profile of the calling user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description update the profile of the calling user, scoped to the JWT subject */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description profile fields to update */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserBody"];
                };
            };
            responses: {
                /** @description profile successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/self/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change user email address
         * @description Request to change the email address. Triggers verification.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Email"];
                };
            };
            responses: {
                /** @description Email change requested, verification sent. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid email or already in use. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication required. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/self/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify a pending email address */
        get: operations["GetAdminSelfEmailVerify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/self/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list the accounts the calling user belongs to, along with their role in each */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list of accounts with roles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSelfAccounts"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new account; the calling user is automatically made the owner */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description information for the new account */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AccountBody"];
                };
            };
            responses: {
                /** @description successfully created account */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ID"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description Quota exceeded */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description global system statistics (admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description system statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_accounts?: number;
                            total_engines?: number;
                            total_databases?: number;
                            total_users?: number;
                            storage_used_bytes?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list all of the accounts for which the authenticated user has access */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list of accounts for my user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedAccounts"];
                    };
                };
                /** @description no accounts available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description create a new account, normally limited to system administrators */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description information for new account */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            responses: {
                /** @description successfully created account */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ID"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description Quota exceeded */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get information about the specific account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description details of the account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete an account (admin only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description account successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description update account details (admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            /** @description account updates */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            responses: {
                /** @description account successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/accounts/{account}/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list backup engines in a given account with row summary fields */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description backup engines for the given account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEngines"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description register a new backup engine in the given account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            /** @description backup engine registration details */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EngineBody"];
                };
            };
            responses: {
                /** @description successfully registered backup engine */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Engine"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description Quota exceeded */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/engines/{engine}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get information about a specific backup engine */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the backup engine */
                    engine: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description details of the backup engine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Engine"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete a specific backup engine */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the backup engine */
                    engine: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description backup engine successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description update a specific backup engine */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the backup engine */
                    engine: string;
                };
                cookie?: never;
            };
            /** @description backup engine updates */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EngineBody"];
                };
            };
            responses: {
                /** @description backup engine successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Engine"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/accounts/{account}/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list protected databases in a given account with row summary fields */
        get: {
            parameters: {
                query?: {
                    /** @description filter to databases protected by a specific backup engine ID */
                    engine?: string;
                    /** @description filter to a specific database engine type */
                    system?: string;
                    /** @description filter to a specific network transport */
                    transport?: string;
                    /** @description filter to a specific hostname, IP, or socket path */
                    address?: string;
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description protected databases for the given account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedDatabases"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description create a protected database record associated with a backup engine */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            /** @description protected database details */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DatabaseBody"];
                };
            };
            responses: {
                /** @description successfully created protected database */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Database"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/databases/{database}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get information about a specific protected database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the database target */
                    database: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description details of the protected database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Database"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete a protected database record */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the database target */
                    database: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description protected database successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description update a protected database record */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the database target */
                    database: string;
                };
                cookie?: never;
            };
            /** @description protected database updates */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DatabaseBody"];
                };
            };
            responses: {
                /** @description protected database successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Database"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/accounts/{account}/databases/{database}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get paginated backup run summaries for a specific protected database; timeline events are not embedded in this list response */
        get: operations["ListDatabaseBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/databases/{database}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get backup log summaries for a specific protected database */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the database target */
                    database: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description backup logs for the specified protected database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedLogSummaries"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get paginated backup run summaries across all protected databases in an account; timeline events are not embedded in this list response */
        get: operations["ListAccountBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/backups/{backup}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get a specific backup run. By default this returns metadata without embedded product timeline events; pass include=events to include the chronological product-level event timeline. */
        get: operations["GetBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/backups/{backup}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get chronological product-level events for exactly one backup run. Events are derived from OTEL traces/spans when available, but the response is product-shaped rather than raw OTEL. */
        get: operations["GetBackupEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/backups/{backup}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get raw trace diagnostic data for exactly one backup run. Product UIs should use backup timeline events for normal status timelines. */
        get: operations["GetBackupTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/logs/{log}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get the backup logs for a specific backup run */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the log */
                    log: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description backup logs for a specific backup run, streamed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedLogs"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/engines/{engine}/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list cloud-managed configs for a specific backup engine */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the backup engine */
                    engine: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description configs for the given backup engine */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationMetadata"] & {
                            configs?: components["schemas"]["Config"][];
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description create a new cloud-managed config for a backup engine */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the backup engine */
                    engine: string;
                };
                cookie?: never;
            };
            /** @description config for the backup engine */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            responses: {
                /** @description successfully created config */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Config"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/configs/{config}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a specific device config */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the config */
                    config: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description details of the config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Config"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete a specific device config */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the config */
                    config: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description config successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list all users in the system (admin only) */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                    /** @description Search term to filter users by name or email */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list of all users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedUsers"];
                    };
                };
            };
        };
        put?: never;
        /** @description create a new user (admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description information for new user */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserWithEmail"];
                };
            };
            responses: {
                /** @description successfully created user */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description delete a user (admin only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique ID of the user */
                    user: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description user successfully deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list users in an account */
        get: {
            parameters: {
                query?: {
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Maximum number of results to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list of users in the account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedAccountMembers"];
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** @description add a user to an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                };
                cookie?: never;
            };
            /** @description user to add to account */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description User ID to add to account */
                        user: string;
                        /** @description Role to assign to the user in the account */
                        role: string;
                    };
                };
            };
            responses: {
                /** @description user successfully added to account */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{account}/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description remove a user from an account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the user */
                    user: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description user successfully removed from account */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description update a user's role in an account */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    account: string;
                    /** @description Unique ID of the user */
                    user: string;
                };
                cookie?: never;
            };
            /** @description role to assign to the user in the account */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Role to assign to the user in the account */
                        role: string;
                    };
                };
            };
            responses: {
                /** @description user successfully updated in account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description information for a new user */
        UserBody: {
            /** @description email address of the user */
            email?: string;
            /** @description full name of the user */
            name?: string;
        };
        Email: {
            /**
             * @description email address of the user
             * @example user@example.com
             */
            email?: string;
        };
        UserWithEmail: components["schemas"]["UserBody"] & components["schemas"]["Email"];
        ID: {
            /**
             * @description unique ID of the object, as a UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
        };
        User: components["schemas"]["UserWithEmail"] & components["schemas"]["ID"];
        PaginationMetadata: {
            total?: number;
            limit?: number;
            offset?: number;
            has_next?: boolean;
            has_prev?: boolean;
        };
        /** @description an account the calling user belongs to, with their role */
        SelfAccountEntry: {
            /**
             * @description unique ID of the account
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /** @description name of the account */
            name?: string;
            /** @description role of the calling user in this account */
            role?: string;
        };
        PaginatedSelfAccounts: components["schemas"]["PaginationMetadata"] & {
            accounts?: components["schemas"]["SelfAccountEntry"][];
        };
        /** @description information for a new databacker account */
        AccountBody: {
            /** @description name of the account */
            name: string;
            /** @description description of the account */
            description?: string;
            /**
             * @description Retention tier for logs/traces (non-numeric label)
             * @enum {string}
             */
            retention_tier?: "basic" | "standard" | "premium" | "custom";
        };
        /** @description information for a databacker account with ID */
        Account: components["schemas"]["AccountBody"] & components["schemas"]["ID"];
        PaginatedAccounts: components["schemas"]["PaginationMetadata"] & {
            accounts?: components["schemas"]["Account"][];
        };
        /** @description backup engine row summary for list views */
        EngineSummary: {
            /** @description Unique identifier of the backup engine */
            id: string;
            /** @description ID of the account that owns the backup engine */
            account_id: string;
            /** @description name of the backup engine */
            name: string;
            /** @description description of the backup engine */
            description?: string | null;
            /** @enum {string} */
            registration_state: "pending" | "registered" | "disabled" | "revoked";
            /** @description number of databases protected by this backup engine */
            database_count: number;
            /** @description database ID when this engine is currently associated with one database */
            connected_database_id?: string | null;
            /** @description database display name when this engine is currently associated with one database */
            connected_database_name?: string | null;
            /** Format: date-time */
            last_seen?: string | null;
            /** Format: date-time */
            last_successful_backup?: string | null;
            /** Format: date-time */
            last_failed_backup?: string | null;
            /** @description status of the latest backup across databases protected by this engine */
            latest_backup_status?: string | null;
            version?: string | null;
            /** @enum {string} */
            config_state: "none" | "local" | "cloud" | "mixed" | "pending" | "drifted";
        };
        PaginatedEngines: components["schemas"]["PaginationMetadata"] & {
            engines?: components["schemas"]["EngineSummary"][];
        };
        /** @description information for a backup engine registration */
        EngineBody: {
            /** @description ECDSA public key to associate with the backup engine, PEM-encoded */
            publicKey?: string;
            /** @description name of the backup engine */
            name: string;
            /** @description description of the backup engine */
            description?: string;
        };
        Engine: components["schemas"]["EngineBody"] & components["schemas"]["ID"] & {
            /** @description ID of the account that owns the backup engine */
            account_id?: string;
            /**
             * @description registration state for the backup engine
             * @enum {string}
             */
            registration_state?: "pending" | "registered" | "disabled" | "revoked";
            /**
             * Format: date-time
             * @description timestamp of the latest heartbeat or authenticated request
             */
            last_seen?: string | null;
            /** @description backup engine software version, if reported */
            version?: string | null;
            /**
             * @description computed configuration state for the backup engine
             * @enum {string}
             */
            config_state?: "none" | "local" | "cloud" | "mixed" | "pending" | "drifted";
            /**
             * Format: date-time
             * @description timestamp when the backup engine was created
             */
            created_at?: string | null;
            /**
             * Format: date-time
             * @description timestamp when the backup engine was last updated
             */
            updated_at?: string | null;
        };
        /** @description protected database row summary for list views */
        DatabaseSummary: {
            /** @description Unique identifier of the database */
            id: string;
            /** @description ID of the account that owns the database */
            account_id: string;
            /** @description ID of the backup engine that protects this database */
            engine_id: string;
            /** @description display name of the backup engine protecting this database */
            engine_name?: string | null;
            /** @description Human-friendly display name for the database */
            name: string;
            /** @description Database engine type */
            system: string;
            /** @description status of the latest backup for this database */
            latest_backup_status?: string | null;
            /**
             * Format: date-time
             * @description timestamp of the latest successful backup for this database
             */
            last_successful_backup?: string | null;
            /**
             * Format: date-time
             * @description timestamp of the latest failed backup for this database
             */
            last_failed_backup?: string | null;
            /** @description error message from the latest failed backup, if available */
            latest_error_message?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the database target was created
             */
            created_at?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the database target was last updated
             */
            updated_at?: string | null;
        };
        PaginatedDatabases: components["schemas"]["PaginationMetadata"] & {
            databases?: components["schemas"]["DatabaseSummary"][];
        };
        /** @description A protected database endpoint or socket used as a backup source. */
        DatabaseBody: {
            /** @description ID of the backup engine that protects this database */
            engine_id: string;
            /** @description Human-friendly display name for the database */
            name: string;
            /**
             * @description Database engine type
             * @example mysql
             */
            system: string;
            /**
             * @description Network transport used to reach the database target
             * @example tcp
             */
            transport: string;
            /** @description Hostname or IP address for TCP, or socket path for unix transport */
            address: string;
            /** @description TCP port for the database target, if applicable */
            port?: number | null;
            /**
             * @deprecated
             * @description Deprecated alias for name retained only for existing stored metadata readers
             */
            display_name?: string | null;
        };
        Database: components["schemas"]["DatabaseBody"] & components["schemas"]["ID"] & {
            /** @description ID of the account that owns the database */
            account_id?: string;
            /** @description display name of the backup engine protecting this database */
            engine_name?: string | null;
            /** @description status of the latest backup for this database */
            latest_backup_status?: string | null;
            /**
             * Format: date-time
             * @description timestamp of the latest successful backup for this database
             */
            last_successful_backup?: string | null;
            /**
             * Format: date-time
             * @description timestamp of the latest failed backup for this database
             */
            last_failed_backup?: string | null;
            /** @description error message from the latest failed backup, if available */
            latest_error_message?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the database was created
             */
            created_at?: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the database was last updated
             */
            updated_at?: string | null;
        };
        /** @description Product-level backup timeline event derived from telemetry when available. */
        BackupTimelineEvent: {
            /** @description Optional stable event identifier */
            id?: string;
            /**
             * Format: date-time
             * @description Event timestamp
             */
            time: string;
            /**
             * @description Product phase for the event
             * @example database_dump
             */
            phase: string;
            /**
             * @description Human-readable event label
             * @example Database dump
             */
            label: string;
            /**
             * @description Product-normalized status
             * @example success
             */
            status?: string;
            /** @description Event duration in milliseconds, if available */
            duration_ms?: number;
            /** @description Human-readable event message */
            message?: string;
            /** @description Product-safe key/value details, not necessarily the full raw OTEL payload */
            attributes?: {
                [key: string]: unknown;
            };
            /** @description Source trace ID, if derived from a trace span */
            trace_id?: string;
            /** @description Source span ID, if derived from a trace span */
            span_id?: string;
            /** @description Source parent span ID, if derived from a trace span */
            parent_span_id?: string | null;
        };
        /** @description Backup run metadata. Product timeline events are only included when requested with include=events. */
        BackupEvent: {
            /**
             * @description unique backup run identifier
             * @example backup-run-id
             */
            id: string;
            /** @description ID of the account the backup belongs to */
            account_id: string;
            /** @description ID of the backup engine that performed the backup */
            engine_id: string;
            /** @description display name of the backup engine at the time of the backup */
            engine_name?: string;
            /** @description ID of the database used for the backup */
            database_id: string;
            /** @description display name of the database at the time of the backup */
            database_name?: string | null;
            /** @description Snapshot of the database engine used by the backup */
            db_system?: string | null;
            /** @description Snapshot of the transport used by the backup */
            network_transport?: string | null;
            /** @description Snapshot of the server hostname, IP, or socket path used by the backup */
            server_address?: string | null;
            /** @description Snapshot of the server port used by the backup, if applicable */
            server_port?: number | null;
            /**
             * Format: date-time
             * @description timestamp for when the backup started
             */
            start_time: string;
            /**
             * Format: date-time
             * @description timestamp for when the backup completed or failed
             */
            end_time?: string;
            /** @description total duration of the backup in milliseconds */
            duration_ms?: number;
            /**
             * @description backup result status, such as success or failure
             * @example success
             */
            status: string;
            /** @description completion code, using a subset of http codes */
            completion?: number;
            /** @description total bytes processed for the backup */
            bytes?: number;
            /** @description ID of the associated backup log, if available */
            log_id?: string;
            /** @description ID of the associated backup trace, if available */
            trace_id?: string;
            /** @description error summary when the backup does not succeed */
            error_message?: string;
            /** @description Chronological product-level timeline events. Only present when backup detail is requested with include=events. */
            events?: components["schemas"]["BackupTimelineEvent"][];
        };
        PaginatedBackupEvents: components["schemas"]["PaginationMetadata"] & {
            /** @description Paginated backup run summaries. List endpoints must not embed product timeline events. */
            events?: components["schemas"]["BackupEvent"][];
        };
        LogSummary: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            id?: string;
            /** @description ID of the database the logs belong to */
            database_id?: string;
            /** @description ID of the backup engine that produced the logs */
            engine_id?: string | null;
            /** @description ID of the account the logs belong to */
            account_id?: string;
            /** @description timestamp for start of backup run */
            date?: number;
            /** @description completion code, using a subset of http codes */
            completion?: number;
            /** @description size of logs in bytes */
            size?: number;
        };
        PaginatedLogSummaries: components["schemas"]["PaginationMetadata"] & {
            logs?: components["schemas"]["LogSummary"][];
        };
        /** @description Chronological product-level events for one backup run. */
        BackupTimelineEvents: {
            /** @description ID of the backup run */
            backup_id: string;
            /** @description ID of the account the backup belongs to */
            account_id: string;
            /** @description ID of the protected database, if available */
            database_id?: string | null;
            /** @description ID of the backup engine, if available */
            engine_id?: string | null;
            /** @description Primary trace ID used to derive events, if available */
            trace_id?: string | null;
            events: components["schemas"]["BackupTimelineEvent"][];
        };
        Span: {
            span_id?: string;
            parent_span_id?: string | null;
            operation_name?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            duration_ms?: number;
            attributes?: {
                [key: string]: unknown;
            };
            /** @description Full OpenTelemetry span payload */
            payload?: {
                [key: string]: unknown;
            };
            children?: components["schemas"]["Span"][];
        };
        /** @description Raw trace diagnostic data for a backup run. */
        Trace: {
            /** Format: uuid */
            trace_id?: string;
            /** @description ID of the backup run this trace belongs to */
            backup_id?: string;
            /** @description ID of the database the trace belongs to */
            database_id?: string;
            /** @description ID of the backup engine that produced the trace */
            engine_id?: string | null;
            /** @description ID of the account the database belongs to */
            account_id?: string;
            root_spans?: components["schemas"]["Span"][];
        };
        /** @description Raw trace diagnostics for one backup run. Product UIs should use backup timeline events for normal status timelines. */
        BackupTraceDiagnostics: {
            /** @description ID of the backup run */
            backup_id: string;
            /** @description ID of the account the backup belongs to */
            account_id: string;
            /** @description ID of the protected database, if available */
            database_id?: string | null;
            /** @description ID of the backup engine, if available */
            engine_id?: string | null;
            traces: components["schemas"]["Trace"][];
        };
        LogLine: {
            /**
             * @description run ID as UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            run?: string;
            /** @description timestamp for the date and time of a message, in RFC3339 format */
            timestamp?: string;
            /** @description log level of the message, one of debug, info, warn, error, fatal */
            level?: string;
            /** @description key-value pairs for descriptive fields for the log message */
            fields?: {
                [key: string]: unknown;
            };
            /** @description actual message */
            message?: string;
        };
        Log: {
            /** @description ID of the database the logs belong to */
            database_id?: string;
            /** @description ID of the backup engine that produced the logs */
            engine_id?: string | null;
            /** @description ID of the account the logs belong to */
            account_id?: string;
            /** @description List of log lines for a backup run */
            lines?: components["schemas"]["LogLine"][];
        };
        PaginatedLogs: components["schemas"]["PaginationMetadata"] & {
            logs?: components["schemas"]["Log"][];
        };
        Metadata: {
            /** @description name of the config */
            name?: string;
            /** @description description of the config */
            description?: string;
            /** @description SHA256 digest of the config, optional */
            digest?: string;
        };
        DBCredentials: {
            /** @description username for the database */
            username?: string;
            /** @description password for the database */
            password?: string;
        };
        "schemas-Database": {
            /** @description hostname:port to database */
            server?: string;
            /** @description port to connect to, defaults to 5432, overrides "server" */
            port?: number;
            credentials?: components["schemas"]["DBCredentials"];
        };
        Schedule: {
            /** @description cron expression for the schedule */
            cron?: string;
            /** @description frequency in minutes */
            frequency?: number;
            /** @description when to start the schedule, in minutes from now, default is 0 */
            begin?: number;
            /** @description whether to run the schedule only once, default is false */
            once?: boolean;
        };
        Encryption: {
            /**
             * @description algorithm to use for encryption
             * @enum {string}
             */
            algorithm?: "aes256-cbc" | "chacha20-poly1305" | "smime-aes256-cbc" | "pbkdf2-aes256-cbc" | "age-chacha20-poly1305";
            /** @description encryption key or certificate, depending on algorithm, base64-encoded */
            key?: string;
            /** @description path to the encryption key or certificate, depending on algorithm */
            keyPath?: string;
        };
        Scripts: {
            /** @description directory where to find scripts to run before the backup */
            preBackup?: string;
            /** @description directory where to find scripts to run after the backup */
            postBackup?: string;
        };
        Dump: {
            /** @description list of database names to backup, defaults to all */
            include?: string[];
            /** @description list of database names to exclude from backup, defaults to none */
            exclude?: string[];
            /** @description whether to use safe characters in the backup name, defaults to false */
            safechars?: boolean;
            /** @description do not include database name in backup, assumes will run restore already selected to specific database */
            noDatabaseName?: boolean;
            /** @description whether to skip extended insert statements and use one insert per row, defaults to false */
            skipExtendedInsert?: boolean;
            schedule?: components["schemas"]["Schedule"];
            /** @description compression algorithm to use, defaults to none */
            compression?: string;
            /** @description whether to compact the backup, defaults to false */
            compact?: boolean;
            /** @description whether to include triggers in the backup, defaults to false */
            triggers?: boolean;
            /** @description whether to include routines, such as functions and procedures, in the backup, defaults to false */
            routines?: boolean;
            /** @description maximum packet size to username */
            maxAllowedPacket?: number;
            /** @description pattern for the filename */
            filenamePattern?: string;
            encryption?: components["schemas"]["Encryption"];
            /** @description list of targets to send the backup, must reference one of the named targets in the config */
            targets?: string[];
            /** @description level of parallelism to use for the backup, defaults to 1 */
            parallelism?: number;
            scripts?: components["schemas"]["Scripts"];
        };
        S3: {
            /** @description region of the bucket */
            region?: string;
            /** @description endpoint URL */
            endpoint?: string;
            /** @description whether to use path-style addressing instead of virtual-host-style, defaults to false */
            pathStyle?: boolean;
            /** @description access key ID */
            accessKeyID?: string;
            /** @description secret access key */
            secretAccessKey?: string;
        };
        SMB: {
            /** @description domain for the username */
            domain?: string;
            /** @description username for the target */
            username?: string;
            /** @description password for the target */
            password?: string;
        };
        File: Record<string, never>;
        /** @description individual backup target */
        Target: {
            /** @enum {string} */
            type: "s3" | "smb" | "file";
            /** @description url to send the backup to */
            url: string;
            spec?: Record<string, never>;
        };
        CommonRemoteDetails: {
            /** @description URL to the remote */
            url?: string;
            /**
             * @description Credentials to use to authenticate to the remote server.
             *     Format is base64-encoded Curve25519 key
             * @example BwMqVfr1myxqX8tikIPYCyNtpHgMLIg/2nUE+pLQnTE=
             */
            credentials?: string;
            /**
             * @description Fingerprints of the remote certificate of the remote server, or one that signed it in the chain.
             *     Starts with hash algorithm, e.g. sha256, followed by a : and the hex of the fingerprint.
             * @example sha256:69729b8e15a86efc177a57afb7171dfc64add28c2fca8cf1507e34453ccb1470
             */
            certificates?: string[];
        };
        Telemetry: components["schemas"]["CommonRemoteDetails"] & {
            /** @description size of the buffer to use for telemetry, in bytes */
            bufferSize?: number;
        };
        Prune: {
            /** @description retention policies for backups */
            retention?: string;
        };
        Restore: {
            /** @description directory where to find scripts to run before the restore */
            preRestore?: string;
            /** @description directory where to find scripts to run after the restore */
            postRestore?: string;
        };
        /** @description configuration details for a databack instance */
        ConfigSpec: {
            /** @description configuration information for accessing database to backup */
            database?: components["schemas"]["schemas-Database"];
            /** @description schedule and details for backups */
            dump?: components["schemas"]["Dump"];
            /**
             * @description Configuration for individual targets that may be used for backup or restore.
             *     To be referenced from within the Dump or Restore configuration.
             */
            targets?: {
                [key: string]: components["schemas"]["Target"];
            };
            telemetry?: components["schemas"]["Telemetry"];
            prune?: components["schemas"]["Prune"];
            restore?: components["schemas"]["Restore"];
            /**
             * @description logging level, one of debug, info, warn, error, fatal
             * @enum {string}
             */
            logging?: "trace" | "debug" | "info" | "warn" | "error";
        };
        /** @description details for retrieving configuration from a remote server */
        RemoteSpec: components["schemas"]["CommonRemoteDetails"];
        /** @description Spec that is encrypted, using the provided algorithm. The symmetric key is encrypted with the public key of the instance. */
        EncryptedSpec: {
            /**
             * @description algorithm used to encrypt the data, lower-case, with the key derived using NaCL key agreement
             * @enum {string}
             */
            algorithm?: "aes256-gcm" | "chacha20-poly1305";
            /** @description public key of the recipient, base64-encoded */
            recipientPublicKey?: string;
            /** @description public key of the recipient, base64-encoded */
            senderPublicKey?: string;
            /** @description encrypted data base64-encoded, when decrypted should be a valid Config */
            data?: string;
        };
        /**
         * @description Base configuration for a databack instance, with details in the spec.
         *     Spec is determined by the kind.
         */
        Config: {
            /** @enum {string} */
            version: "config.databack.io/v1";
            /** @enum {string} */
            kind: "local" | "remote" | "encrypted";
            metadata: components["schemas"]["Metadata"];
            spec: Record<string, never>;
        };
        PaginatedUsers: components["schemas"]["PaginationMetadata"] & {
            users?: components["schemas"]["User"][];
        };
        AccountMember: {
            /** @description unique ID of the user */
            user: string;
            /**
             * @description role of the user in the account
             * @enum {string}
             */
            role: "owner" | "admin" | "member" | "viewer";
        };
        PaginatedAccountMembers: components["schemas"]["PaginationMetadata"] & {
            users?: components["schemas"]["AccountMember"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAdminSelfEmailVerify: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListDatabaseBackups: {
        parameters: {
            query?: {
                /** @description backup status to filter by */
                status?: string;
                start_time?: string;
                end_time?: string;
                /** @description when true, return only the latest backup event for this database */
                latest_per_database?: boolean;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Account ID */
                account: string;
                /** @description Unique ID of the database target */
                database: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description backup summaries for the specified protected database */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBackupEvents"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListAccountBackups: {
        parameters: {
            query?: {
                /** @description filter to backups produced by a specific backup engine ID */
                engine?: string;
                /** @description filter to backups for a specific protected database ID */
                database?: string;
                /** @description backup status to filter by */
                status?: string;
                start_time?: string;
                end_time?: string;
                /** @description when true, return only the latest backup event per protected database */
                latest_per_database?: boolean;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Account ID */
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description backup summaries for the account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBackupEvents"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBackup: {
        parameters: {
            query?: {
                /** @description include=events embeds product-level backup timeline events in the response */
                include?: "events";
            };
            header?: never;
            path: {
                /** @description Account ID */
                account: string;
                /** @description Unique ID of the backup run */
                backup: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description backup run details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupEvent"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBackupEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                account: string;
                /** @description Unique ID of the backup run */
                backup: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description product-level backup timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupTimelineEvents"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBackupTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                account: string;
                /** @description Unique ID of the backup run */
                backup: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description raw trace diagnostics for a backup run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupTraceDiagnostics"];
                };
            };
            /** @description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
