// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	externalRef0 "github.com/databacker/api/go/api"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	JWTScopes = "JWT.Scopes"
)

// GetAdminInstancesParams defines parameters for GetAdminInstances.
type GetAdminInstancesParams struct {
	// Account Account IDs for which to retrieve list of instances
	Account string `form:"account" json:"account" yaml:"account"`
}

// PostAdminInstancesParams defines parameters for PostAdminInstances.
type PostAdminInstancesParams struct {
	// Account Account ID for which to create a new instance
	Account string `form:"account" json:"account" yaml:"account"`
}

// GetAdminInstancesInstanceTracesParams defines parameters for GetAdminInstancesInstanceTraces.
type GetAdminInstancesInstanceTracesParams struct {
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty" yaml:"start_time,omitempty"`
	EndTime   *time.Time `form:"end_time,omitempty" json:"end_time,omitempty" yaml:"end_time,omitempty"`

	// Attribute key=value filter (repeatable)
	Attribute     *string  `form:"attribute,omitempty" json:"attribute,omitempty" yaml:"attribute,omitempty"`
	MinDurationMs *float32 `form:"min_duration_ms,omitempty" json:"min_duration_ms,omitempty" yaml:"min_duration_ms,omitempty"`
	Limit         *int     `form:"limit,omitempty" json:"limit,omitempty" yaml:"limit,omitempty"`
}

// PostAdminConfigsJSONRequestBody defines body for PostAdminConfigs for application/json ContentType.
type PostAdminConfigsJSONRequestBody = externalRef0.Config

// PostAdminInstancesJSONRequestBody defines body for PostAdminInstances for application/json ContentType.
type PostAdminInstancesJSONRequestBody = NewInstance

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /admin/configs)
	PostAdminConfigs(w http.ResponseWriter, r *http.Request)

	// (GET /admin/configs/{config})
	GetAdminConfigsConfig(w http.ResponseWriter, r *http.Request, config string)

	// (GET /admin/instances)
	GetAdminInstances(w http.ResponseWriter, r *http.Request, params GetAdminInstancesParams)

	// (POST /admin/instances)
	PostAdminInstances(w http.ResponseWriter, r *http.Request, params PostAdminInstancesParams)

	// (GET /admin/instances/{instance})
	GetAdminInstancesInstance(w http.ResponseWriter, r *http.Request, instance string)

	// (GET /admin/instances/{instance}/logs)
	GetAdminInstancesInstanceLogs(w http.ResponseWriter, r *http.Request, instance string)

	// (GET /admin/instances/{instance}/traces)
	GetAdminInstancesInstanceTraces(w http.ResponseWriter, r *http.Request, instance string, params GetAdminInstancesInstanceTracesParams)

	// (GET /admin/logs/{log})
	GetAdminLogsLog(w http.ResponseWriter, r *http.Request, log string)

	// (GET /admin/traces/{trace})
	GetAdminTracesTrace(w http.ResponseWriter, r *http.Request, trace string)

	// (GET /admin/traces/{trace}/spans/{span})
	GetAdminTracesTraceSpansSpan(w http.ResponseWriter, r *http.Request, trace string, span string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /admin/configs)
func (_ Unimplemented) PostAdminConfigs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/configs/{config})
func (_ Unimplemented) GetAdminConfigsConfig(w http.ResponseWriter, r *http.Request, config string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/instances)
func (_ Unimplemented) GetAdminInstances(w http.ResponseWriter, r *http.Request, params GetAdminInstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /admin/instances)
func (_ Unimplemented) PostAdminInstances(w http.ResponseWriter, r *http.Request, params PostAdminInstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/instances/{instance})
func (_ Unimplemented) GetAdminInstancesInstance(w http.ResponseWriter, r *http.Request, instance string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/instances/{instance}/logs)
func (_ Unimplemented) GetAdminInstancesInstanceLogs(w http.ResponseWriter, r *http.Request, instance string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/instances/{instance}/traces)
func (_ Unimplemented) GetAdminInstancesInstanceTraces(w http.ResponseWriter, r *http.Request, instance string, params GetAdminInstancesInstanceTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/logs/{log})
func (_ Unimplemented) GetAdminLogsLog(w http.ResponseWriter, r *http.Request, log string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/traces/{trace})
func (_ Unimplemented) GetAdminTracesTrace(w http.ResponseWriter, r *http.Request, trace string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /admin/traces/{trace}/spans/{span})
func (_ Unimplemented) GetAdminTracesTraceSpansSpan(w http.ResponseWriter, r *http.Request, trace string, span string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminConfigs operation middleware
func (siw *ServerInterfaceWrapper) PostAdminConfigs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminConfigs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminConfigsConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAdminConfigsConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "config" -------------
	var config string

	err = runtime.BindStyledParameterWithOptions("simple", "config", chi.URLParam(r, "config"), &config, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "config", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminConfigsConfig(w, r, config)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminInstances operation middleware
func (siw *ServerInterfaceWrapper) GetAdminInstances(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminInstancesParams

	// ------------- Required query parameter "account" -------------

	if paramValue := r.URL.Query().Get("account"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "account"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "account", r.URL.Query(), &params.Account)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminInstances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminInstances operation middleware
func (siw *ServerInterfaceWrapper) PostAdminInstances(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAdminInstancesParams

	// ------------- Required query parameter "account" -------------

	if paramValue := r.URL.Query().Get("account"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "account"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "account", r.URL.Query(), &params.Account)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminInstances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminInstancesInstance operation middleware
func (siw *ServerInterfaceWrapper) GetAdminInstancesInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", chi.URLParam(r, "instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminInstancesInstance(w, r, instance)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminInstancesInstanceLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAdminInstancesInstanceLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", chi.URLParam(r, "instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminInstancesInstanceLogs(w, r, instance)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminInstancesInstanceTraces operation middleware
func (siw *ServerInterfaceWrapper) GetAdminInstancesInstanceTraces(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instance" -------------
	var instance string

	err = runtime.BindStyledParameterWithOptions("simple", "instance", chi.URLParam(r, "instance"), &instance, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instance", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminInstancesInstanceTracesParams

	// ------------- Optional query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time", r.URL.Query(), &params.StartTime)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_time", Err: err})
		return
	}

	// ------------- Optional query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_time", r.URL.Query(), &params.EndTime)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_time", Err: err})
		return
	}

	// ------------- Optional query parameter "attribute" -------------

	err = runtime.BindQueryParameter("form", true, false, "attribute", r.URL.Query(), &params.Attribute)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "attribute", Err: err})
		return
	}

	// ------------- Optional query parameter "min_duration_ms" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_duration_ms", r.URL.Query(), &params.MinDurationMs)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_duration_ms", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminInstancesInstanceTraces(w, r, instance, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminLogsLog operation middleware
func (siw *ServerInterfaceWrapper) GetAdminLogsLog(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "log" -------------
	var log string

	err = runtime.BindStyledParameterWithOptions("simple", "log", chi.URLParam(r, "log"), &log, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "log", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminLogsLog(w, r, log)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminTracesTrace operation middleware
func (siw *ServerInterfaceWrapper) GetAdminTracesTrace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trace" -------------
	var trace string

	err = runtime.BindStyledParameterWithOptions("simple", "trace", chi.URLParam(r, "trace"), &trace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trace", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminTracesTrace(w, r, trace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminTracesTraceSpansSpan operation middleware
func (siw *ServerInterfaceWrapper) GetAdminTracesTraceSpansSpan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trace" -------------
	var trace string

	err = runtime.BindStyledParameterWithOptions("simple", "trace", chi.URLParam(r, "trace"), &trace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trace", Err: err})
		return
	}

	// ------------- Path parameter "span" -------------
	var span string

	err = runtime.BindStyledParameterWithOptions("simple", "span", chi.URLParam(r, "span"), &span, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "span", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, JWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminTracesTraceSpansSpan(w, r, trace, span)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/configs", wrapper.PostAdminConfigs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/configs/{config}", wrapper.GetAdminConfigsConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/instances", wrapper.GetAdminInstances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/instances", wrapper.PostAdminInstances)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/instances/{instance}", wrapper.GetAdminInstancesInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/instances/{instance}/logs", wrapper.GetAdminInstancesInstanceLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/instances/{instance}/traces", wrapper.GetAdminInstancesInstanceTraces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/logs/{log}", wrapper.GetAdminLogsLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/traces/{trace}", wrapper.GetAdminTracesTrace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/traces/{trace}/spans/{span}", wrapper.GetAdminTracesTraceSpansSpan)
	})

	return r
}

type PostAdminConfigsRequestObject struct {
	Body *PostAdminConfigsJSONRequestBody
}

type PostAdminConfigsResponseObject interface {
	VisitPostAdminConfigsResponse(w http.ResponseWriter) error
}

type PostAdminConfigs201JSONResponse externalRef0.Config

func (response PostAdminConfigs201JSONResponse) VisitPostAdminConfigsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostAdminConfigs400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response PostAdminConfigs400JSONResponse) VisitPostAdminConfigsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminConfigsConfigRequestObject struct {
	Config string `json:"config"`
}

type GetAdminConfigsConfigResponseObject interface {
	VisitGetAdminConfigsConfigResponse(w http.ResponseWriter) error
}

type GetAdminConfigsConfig200JSONResponse externalRef0.Config

func (response GetAdminConfigsConfig200JSONResponse) VisitGetAdminConfigsConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminConfigsConfig404Response struct {
}

func (response GetAdminConfigsConfig404Response) VisitGetAdminConfigsConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminInstancesRequestObject struct {
	Params GetAdminInstancesParams
}

type GetAdminInstancesResponseObject interface {
	VisitGetAdminInstancesResponse(w http.ResponseWriter) error
}

type GetAdminInstances200JSONResponse []string

func (response GetAdminInstances200JSONResponse) VisitGetAdminInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminInstances404Response struct {
}

func (response GetAdminInstances404Response) VisitGetAdminInstancesResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostAdminInstancesRequestObject struct {
	Params PostAdminInstancesParams
	Body   *PostAdminInstancesJSONRequestBody
}

type PostAdminInstancesResponseObject interface {
	VisitPostAdminInstancesResponse(w http.ResponseWriter) error
}

type PostAdminInstances201JSONResponse InstanceBody

func (response PostAdminInstances201JSONResponse) VisitPostAdminInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostAdminInstances400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response PostAdminInstances400JSONResponse) VisitPostAdminInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAdminInstances422JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response PostAdminInstances422JSONResponse) VisitPostAdminInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminInstancesInstanceRequestObject struct {
	Instance string `json:"instance"`
}

type GetAdminInstancesInstanceResponseObject interface {
	VisitGetAdminInstancesInstanceResponse(w http.ResponseWriter) error
}

type GetAdminInstancesInstance200JSONResponse InstanceBody

func (response GetAdminInstancesInstance200JSONResponse) VisitGetAdminInstancesInstanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminInstancesInstance404Response struct {
}

func (response GetAdminInstancesInstance404Response) VisitGetAdminInstancesInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminInstancesInstanceLogsRequestObject struct {
	Instance string `json:"instance"`
}

type GetAdminInstancesInstanceLogsResponseObject interface {
	VisitGetAdminInstancesInstanceLogsResponse(w http.ResponseWriter) error
}

type GetAdminInstancesInstanceLogs200JSONResponse []LogSummary

func (response GetAdminInstancesInstanceLogs200JSONResponse) VisitGetAdminInstancesInstanceLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminInstancesInstanceLogs404Response struct {
}

func (response GetAdminInstancesInstanceLogs404Response) VisitGetAdminInstancesInstanceLogsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminInstancesInstanceTracesRequestObject struct {
	Instance string `json:"instance"`
	Params   GetAdminInstancesInstanceTracesParams
}

type GetAdminInstancesInstanceTracesResponseObject interface {
	VisitGetAdminInstancesInstanceTracesResponse(w http.ResponseWriter) error
}

type GetAdminInstancesInstanceTraces200JSONResponse []TraceSummary

func (response GetAdminInstancesInstanceTraces200JSONResponse) VisitGetAdminInstancesInstanceTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminInstancesInstanceTraces404Response struct {
}

func (response GetAdminInstancesInstanceTraces404Response) VisitGetAdminInstancesInstanceTracesResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminLogsLogRequestObject struct {
	Log string `json:"log"`
}

type GetAdminLogsLogResponseObject interface {
	VisitGetAdminLogsLogResponse(w http.ResponseWriter) error
}

type GetAdminLogsLog200JSONResponse []Log

func (response GetAdminLogsLog200JSONResponse) VisitGetAdminLogsLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminLogsLog404Response struct {
}

func (response GetAdminLogsLog404Response) VisitGetAdminLogsLogResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminTracesTraceRequestObject struct {
	Trace string `json:"trace"`
}

type GetAdminTracesTraceResponseObject interface {
	VisitGetAdminTracesTraceResponse(w http.ResponseWriter) error
}

type GetAdminTracesTrace200JSONResponse []Trace

func (response GetAdminTracesTrace200JSONResponse) VisitGetAdminTracesTraceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminTracesTrace404Response struct {
}

func (response GetAdminTracesTrace404Response) VisitGetAdminTracesTraceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAdminTracesTraceSpansSpanRequestObject struct {
	Trace string `json:"trace"`
	Span  string `json:"span"`
}

type GetAdminTracesTraceSpansSpanResponseObject interface {
	VisitGetAdminTracesTraceSpansSpanResponse(w http.ResponseWriter) error
}

type GetAdminTracesTraceSpansSpan200JSONResponse []Span

func (response GetAdminTracesTraceSpansSpan200JSONResponse) VisitGetAdminTracesTraceSpansSpanResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminTracesTraceSpansSpan404Response struct {
}

func (response GetAdminTracesTraceSpansSpan404Response) VisitGetAdminTracesTraceSpansSpanResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /admin/configs)
	PostAdminConfigs(ctx context.Context, request PostAdminConfigsRequestObject) (PostAdminConfigsResponseObject, error)

	// (GET /admin/configs/{config})
	GetAdminConfigsConfig(ctx context.Context, request GetAdminConfigsConfigRequestObject) (GetAdminConfigsConfigResponseObject, error)

	// (GET /admin/instances)
	GetAdminInstances(ctx context.Context, request GetAdminInstancesRequestObject) (GetAdminInstancesResponseObject, error)

	// (POST /admin/instances)
	PostAdminInstances(ctx context.Context, request PostAdminInstancesRequestObject) (PostAdminInstancesResponseObject, error)

	// (GET /admin/instances/{instance})
	GetAdminInstancesInstance(ctx context.Context, request GetAdminInstancesInstanceRequestObject) (GetAdminInstancesInstanceResponseObject, error)

	// (GET /admin/instances/{instance}/logs)
	GetAdminInstancesInstanceLogs(ctx context.Context, request GetAdminInstancesInstanceLogsRequestObject) (GetAdminInstancesInstanceLogsResponseObject, error)

	// (GET /admin/instances/{instance}/traces)
	GetAdminInstancesInstanceTraces(ctx context.Context, request GetAdminInstancesInstanceTracesRequestObject) (GetAdminInstancesInstanceTracesResponseObject, error)

	// (GET /admin/logs/{log})
	GetAdminLogsLog(ctx context.Context, request GetAdminLogsLogRequestObject) (GetAdminLogsLogResponseObject, error)

	// (GET /admin/traces/{trace})
	GetAdminTracesTrace(ctx context.Context, request GetAdminTracesTraceRequestObject) (GetAdminTracesTraceResponseObject, error)

	// (GET /admin/traces/{trace}/spans/{span})
	GetAdminTracesTraceSpansSpan(ctx context.Context, request GetAdminTracesTraceSpansSpanRequestObject) (GetAdminTracesTraceSpansSpanResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAdminConfigs operation middleware
func (sh *strictHandler) PostAdminConfigs(w http.ResponseWriter, r *http.Request) {
	var request PostAdminConfigsRequestObject

	var body PostAdminConfigsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminConfigs(ctx, request.(PostAdminConfigsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminConfigs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminConfigsResponseObject); ok {
		if err := validResponse.VisitPostAdminConfigsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminConfigsConfig operation middleware
func (sh *strictHandler) GetAdminConfigsConfig(w http.ResponseWriter, r *http.Request, config string) {
	var request GetAdminConfigsConfigRequestObject

	request.Config = config

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminConfigsConfig(ctx, request.(GetAdminConfigsConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminConfigsConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminConfigsConfigResponseObject); ok {
		if err := validResponse.VisitGetAdminConfigsConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminInstances operation middleware
func (sh *strictHandler) GetAdminInstances(w http.ResponseWriter, r *http.Request, params GetAdminInstancesParams) {
	var request GetAdminInstancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminInstances(ctx, request.(GetAdminInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminInstancesResponseObject); ok {
		if err := validResponse.VisitGetAdminInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAdminInstances operation middleware
func (sh *strictHandler) PostAdminInstances(w http.ResponseWriter, r *http.Request, params PostAdminInstancesParams) {
	var request PostAdminInstancesRequestObject

	request.Params = params

	var body PostAdminInstancesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminInstances(ctx, request.(PostAdminInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminInstancesResponseObject); ok {
		if err := validResponse.VisitPostAdminInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminInstancesInstance operation middleware
func (sh *strictHandler) GetAdminInstancesInstance(w http.ResponseWriter, r *http.Request, instance string) {
	var request GetAdminInstancesInstanceRequestObject

	request.Instance = instance

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminInstancesInstance(ctx, request.(GetAdminInstancesInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminInstancesInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminInstancesInstanceResponseObject); ok {
		if err := validResponse.VisitGetAdminInstancesInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminInstancesInstanceLogs operation middleware
func (sh *strictHandler) GetAdminInstancesInstanceLogs(w http.ResponseWriter, r *http.Request, instance string) {
	var request GetAdminInstancesInstanceLogsRequestObject

	request.Instance = instance

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminInstancesInstanceLogs(ctx, request.(GetAdminInstancesInstanceLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminInstancesInstanceLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminInstancesInstanceLogsResponseObject); ok {
		if err := validResponse.VisitGetAdminInstancesInstanceLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminInstancesInstanceTraces operation middleware
func (sh *strictHandler) GetAdminInstancesInstanceTraces(w http.ResponseWriter, r *http.Request, instance string, params GetAdminInstancesInstanceTracesParams) {
	var request GetAdminInstancesInstanceTracesRequestObject

	request.Instance = instance
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminInstancesInstanceTraces(ctx, request.(GetAdminInstancesInstanceTracesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminInstancesInstanceTraces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminInstancesInstanceTracesResponseObject); ok {
		if err := validResponse.VisitGetAdminInstancesInstanceTracesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminLogsLog operation middleware
func (sh *strictHandler) GetAdminLogsLog(w http.ResponseWriter, r *http.Request, log string) {
	var request GetAdminLogsLogRequestObject

	request.Log = log

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminLogsLog(ctx, request.(GetAdminLogsLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminLogsLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminLogsLogResponseObject); ok {
		if err := validResponse.VisitGetAdminLogsLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminTracesTrace operation middleware
func (sh *strictHandler) GetAdminTracesTrace(w http.ResponseWriter, r *http.Request, trace string) {
	var request GetAdminTracesTraceRequestObject

	request.Trace = trace

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminTracesTrace(ctx, request.(GetAdminTracesTraceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminTracesTrace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminTracesTraceResponseObject); ok {
		if err := validResponse.VisitGetAdminTracesTraceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminTracesTraceSpansSpan operation middleware
func (sh *strictHandler) GetAdminTracesTraceSpansSpan(w http.ResponseWriter, r *http.Request, trace string, span string) {
	var request GetAdminTracesTraceSpansSpanRequestObject

	request.Trace = trace
	request.Span = span

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminTracesTraceSpansSpan(ctx, request.(GetAdminTracesTraceSpansSpanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminTracesTraceSpansSpan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminTracesTraceSpansSpanResponseObject); ok {
		if err := validResponse.VisitGetAdminTracesTraceSpansSpanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
