// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Account information for a new databacker account
type Account struct {
	// Email email address associated with the account
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`

	// Name name of the owner the account
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Phone phone number associated with the account
	Phone *string `json:"phone,omitempty" yaml:"phone,omitempty"`
}

// AccountBody defines model for AccountBody.
type AccountBody struct {
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`
}

// AccountWithID defines model for AccountWithID.
type AccountWithID struct {
	// Email email address associated with the account
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`
	ID    *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Name name of the owner the account
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Phone phone number associated with the account
	Phone *string `json:"phone,omitempty" yaml:"phone,omitempty"`
}

// FlatTrace defines model for FlatTrace.
type FlatTrace struct {
	// AccountID ID of the account the instance belongs to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// InstanceID ID of the instance the trace belongs to
	InstanceID *string     `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`
	Spans      *[]SpanFlat `json:"spans,omitempty" yaml:"spans,omitempty"`
	TraceID    *string     `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// InstanceBody defines model for InstanceBody.
type InstanceBody struct {
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`
}

// Log defines model for Log.
type Log struct {
	// AccountID ID of the account the logs belong to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// InstanceID ID of the instance the logs belong to
	InstanceID *string `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`

	// Lines List of log lines for a backup run
	Lines *[]LogLine `json:"lines,omitempty" yaml:"lines,omitempty"`
}

// LogLine defines model for LogLine.
type LogLine struct {
	// Fields key-value pairs for descriptive fields for the log message
	Fields *map[string]interface{} `json:"fields,omitempty" yaml:"fields,omitempty"`

	// Level log level of the message, one of debug, info, warn, error, fatal
	Level *string `json:"level,omitempty" yaml:"level,omitempty"`

	// Message actual message
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// Run run ID as UUID
	Run *string `json:"run,omitempty" yaml:"run,omitempty"`

	// Timestamp timestamp for the date and time of a message, in RFC3339 format
	Timestamp *string `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
}

// LogSummary defines model for LogSummary.
type LogSummary struct {
	// AccountID ID of the account the logs belong to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// Completion completion code, using a subset of http codes
	Completion *int `json:"completion,omitempty" yaml:"completion,omitempty"`

	// Date timestamp for start of backup run
	Date *int    `json:"date,omitempty" yaml:"date,omitempty"`
	ID   *string `json:"id,omitempty" yaml:"id,omitempty"`

	// InstanceID ID of the instance the logs belong to
	InstanceID *string `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`

	// Size size of logs in bytes
	Size *int `json:"size,omitempty" yaml:"size,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	// Description description of the config
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// Digest SHA256 digest of the config, optional
	Digest *string `json:"digest,omitempty" yaml:"digest,omitempty"`

	// Name name of the config
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

// NewInstance information for a new licensed databacker instance
type NewInstance struct {
	// Description description of the instance
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// Name name of the instance
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// PublicKey ECDSA public key to associate with the instance, PEM-encoded
	PublicKey *string `json:"publicKey,omitempty" yaml:"publicKey,omitempty"`
}

// NewUser information for a new user
type NewUser struct {
	// Email email address of the user
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`

	// Name full name of the user
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

// Span defines model for Span.
type Span struct {
	Attributes    *map[string]interface{} `json:"attributes,omitempty" yaml:"attributes,omitempty"`
	Children      *[]Span                 `json:"children,omitempty" yaml:"children,omitempty"`
	DurationMs    *float32                `json:"duration_ms,omitempty" yaml:"duration_ms,omitempty"`
	EndTime       *time.Time              `json:"end_time,omitempty" yaml:"end_time,omitempty"`
	OperationName *string                 `json:"operation_name,omitempty" yaml:"operation_name,omitempty"`
	ParentSpanID  *string                 `json:"parent_span_id" yaml:"parent_span_id"`

	// Payload Full OpenTelemetry span payload
	Payload   *map[string]interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`
	SpanID    *string                 `json:"span_id,omitempty" yaml:"span_id,omitempty"`
	StartTime *time.Time              `json:"start_time,omitempty" yaml:"start_time,omitempty"`
}

// SpanFlat defines model for SpanFlat.
type SpanFlat struct {
	Attributes    *map[string]interface{} `json:"attributes,omitempty" yaml:"attributes,omitempty"`
	EndTime       *time.Time              `json:"end_time,omitempty" yaml:"end_time,omitempty"`
	OperationName *string                 `json:"operation_name,omitempty" yaml:"operation_name,omitempty"`
	ParentSpanID  *string                 `json:"parent_span_id" yaml:"parent_span_id"`
	Payload       *map[string]interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`
	SpanID        *string                 `json:"span_id,omitempty" yaml:"span_id,omitempty"`
	StartTime     *time.Time              `json:"start_time,omitempty" yaml:"start_time,omitempty"`
}

// Trace defines model for Trace.
type Trace struct {
	// AccountID ID of the account the instance belongs to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// InstanceID ID of the instance the trace belongs to
	InstanceID *string             `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`
	RootSpans  *[]Span             `json:"root_spans,omitempty" yaml:"root_spans,omitempty"`
	TraceID    *openapi_types.UUID `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// TraceSearchResponse defines model for TraceSearchResponse.
type TraceSearchResponse struct {
	Traces *[]TraceSummary `json:"traces,omitempty" yaml:"traces,omitempty"`
}

// TraceSummary defines model for TraceSummary.
type TraceSummary struct {
	// AccountID ID of the account the instance belongs to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// Completion completion code, using a subset of http codes
	Completion *int `json:"completion,omitempty" yaml:"completion,omitempty"`

	// Date timestamp for start of backup run
	Date *int    `json:"date,omitempty" yaml:"date,omitempty"`
	ID   *string `json:"id,omitempty" yaml:"id,omitempty"`

	// InstanceID ID of the instance the trace belongs to
	InstanceID *string `json:"instance_id,omitempty" yaml:"instance_id,omitempty"`

	// Size size of trace in bytes
	Size *int `json:"size,omitempty" yaml:"size,omitempty"`
}

// UserBody defines model for UserBody.
type UserBody struct {
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`
	ID    *string `json:"id,omitempty" yaml:"id,omitempty"`
	Name  *string `json:"name,omitempty" yaml:"name,omitempty"`
}
