// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountRetentionTier.
const (
	AccountRetentionTierBasic    AccountRetentionTier = "basic"
	AccountRetentionTierCustom   AccountRetentionTier = "custom"
	AccountRetentionTierPremium  AccountRetentionTier = "premium"
	AccountRetentionTierStandard AccountRetentionTier = "standard"
)

// Defines values for AccountBodyRetentionTier.
const (
	AccountBodyRetentionTierBasic    AccountBodyRetentionTier = "basic"
	AccountBodyRetentionTierCustom   AccountBodyRetentionTier = "custom"
	AccountBodyRetentionTierPremium  AccountBodyRetentionTier = "premium"
	AccountBodyRetentionTierStandard AccountBodyRetentionTier = "standard"
)

// Defines values for AccountMemberRole.
const (
	Admin  AccountMemberRole = "admin"
	Member AccountMemberRole = "member"
	Owner  AccountMemberRole = "owner"
	Viewer AccountMemberRole = "viewer"
)

// Defines values for BillingEntitlementActivationReason.
const (
	BillingEntitlementActivationReasonAutomaticDiscovery   BillingEntitlementActivationReason = "automatic_discovery"
	BillingEntitlementActivationReasonExplicitReactivation BillingEntitlementActivationReason = "explicit_reactivation"
	BillingEntitlementActivationReasonManualActivation     BillingEntitlementActivationReason = "manual_activation"
)

// Defines values for BillingEntitlementDeactivationReason.
const (
	BillingEntitlementDeactivationReasonAccountClosed BillingEntitlementDeactivationReason = "account_closed"
	BillingEntitlementDeactivationReasonCorrection    BillingEntitlementDeactivationReason = "correction"
	BillingEntitlementDeactivationReasonUserRequested BillingEntitlementDeactivationReason = "user_requested"
)

// Defines values for BillingPriceInterval.
const (
	Month BillingPriceInterval = "month"
)

// Defines values for BillingProductBillableUnit.
const (
	ActiveProtectedDatabase BillingProductBillableUnit = "active_protected_database"
)

// Defines values for BillingReadinessReason.
const (
	CreditOnlyPolicy                 BillingReadinessReason = "credit_only_policy"
	NoReusablePaymentMethod          BillingReadinessReason = "no_reusable_payment_method"
	ProviderConfirmedPaymentMethod   BillingReadinessReason = "provider_confirmed_payment_method"
	ProviderPaymentMethodInvalidated BillingReadinessReason = "provider_payment_method_invalidated"
	ProviderSyncPending              BillingReadinessReason = "provider_sync_pending"
)

// Defines values for BillingReadinessState.
const (
	BillingReady                BillingReadinessState = "billing_ready"
	Dormant                     BillingReadinessState = "dormant"
	NotReady                    BillingReadinessState = "not_ready"
	PendingProviderConfirmation BillingReadinessState = "pending_provider_confirmation"
)

// Defines values for DatabaseProtectionLifecycleActivationReason.
const (
	DatabaseProtectionLifecycleActivationReasonAutomaticDiscovery   DatabaseProtectionLifecycleActivationReason = "automatic_discovery"
	DatabaseProtectionLifecycleActivationReasonExplicitReactivation DatabaseProtectionLifecycleActivationReason = "explicit_reactivation"
	DatabaseProtectionLifecycleActivationReasonManualActivation     DatabaseProtectionLifecycleActivationReason = "manual_activation"
)

// Defines values for DatabaseProtectionLifecycleDeactivationReason.
const (
	DatabaseProtectionLifecycleDeactivationReasonAccountClosed DatabaseProtectionLifecycleDeactivationReason = "account_closed"
	DatabaseProtectionLifecycleDeactivationReasonCorrection    DatabaseProtectionLifecycleDeactivationReason = "correction"
	DatabaseProtectionLifecycleDeactivationReasonUserRequested DatabaseProtectionLifecycleDeactivationReason = "user_requested"
)

// Defines values for DatabaseProtectionLifecycleState.
const (
	Active              DatabaseProtectionLifecycleState = "active"
	BlockedActivation   DatabaseProtectionLifecycleState = "blocked_activation"
	Deactivated         DatabaseProtectionLifecycleState = "deactivated"
	PendingReactivation DatabaseProtectionLifecycleState = "pending_reactivation"
)

// Defines values for EmailChangePendingStatus.
const (
	VerificationRequired EmailChangePendingStatus = "verification_required"
)

// Defines values for EngineConfigState.
const (
	EngineConfigStateCloud   EngineConfigState = "cloud"
	EngineConfigStateDrifted EngineConfigState = "drifted"
	EngineConfigStateLocal   EngineConfigState = "local"
	EngineConfigStateMixed   EngineConfigState = "mixed"
	EngineConfigStateNone    EngineConfigState = "none"
	EngineConfigStatePending EngineConfigState = "pending"
)

// Defines values for EngineRegistrationState.
const (
	EngineRegistrationStateDisabled   EngineRegistrationState = "disabled"
	EngineRegistrationStatePending    EngineRegistrationState = "pending"
	EngineRegistrationStateRegistered EngineRegistrationState = "registered"
	EngineRegistrationStateRevoked    EngineRegistrationState = "revoked"
)

// Defines values for EngineSummaryConfigState.
const (
	EngineSummaryConfigStateCloud   EngineSummaryConfigState = "cloud"
	EngineSummaryConfigStateDrifted EngineSummaryConfigState = "drifted"
	EngineSummaryConfigStateLocal   EngineSummaryConfigState = "local"
	EngineSummaryConfigStateMixed   EngineSummaryConfigState = "mixed"
	EngineSummaryConfigStateNone    EngineSummaryConfigState = "none"
	EngineSummaryConfigStatePending EngineSummaryConfigState = "pending"
)

// Defines values for EngineSummaryRegistrationState.
const (
	EngineSummaryRegistrationStateDisabled   EngineSummaryRegistrationState = "disabled"
	EngineSummaryRegistrationStatePending    EngineSummaryRegistrationState = "pending"
	EngineSummaryRegistrationStateRegistered EngineSummaryRegistrationState = "registered"
	EngineSummaryRegistrationStateRevoked    EngineSummaryRegistrationState = "revoked"
)

// Defines values for InvoiceArtifactArtifactType.
const (
	HTML             InvoiceArtifactArtifactType = "html"
	Pdf              InvoiceArtifactArtifactType = "pdf"
	ProviderRedirect InvoiceArtifactArtifactType = "provider_redirect"
)

// Defines values for InvoiceSummaryStatus.
const (
	Finalized     InvoiceSummaryStatus = "finalized"
	Open          InvoiceSummaryStatus = "open"
	Paid          InvoiceSummaryStatus = "paid"
	Uncollectible InvoiceSummaryStatus = "uncollectible"
	Void          InvoiceSummaryStatus = "void"
)

// Defines values for PaymentMethodDisplayStatus.
const (
	Invalidated   PaymentMethodDisplayStatus = "invalidated"
	None          PaymentMethodDisplayStatus = "none"
	Pending       PaymentMethodDisplayStatus = "pending"
	SavedReusable PaymentMethodDisplayStatus = "saved_reusable"
)

// Defines values for PendingReactivationSummaryLatestReportStatus.
const (
	Ignored               PendingReactivationSummaryLatestReportStatus = "ignored"
	RejectedLimitExceeded PendingReactivationSummaryLatestReportStatus = "rejected_limit_exceeded"
	Retained              PendingReactivationSummaryLatestReportStatus = "retained"
)

// Defines values for PortalSessionPurpose.
const (
	PortalSessionPurposeCommercialProfileManagement PortalSessionPurpose = "commercial_profile_management"
	PortalSessionPurposeGeneral                     PortalSessionPurpose = "general"
	PortalSessionPurposeInvoiceSelfService          PortalSessionPurpose = "invoice_self_service"
	PortalSessionPurposePaymentMethodManagement     PortalSessionPurpose = "payment_method_management"
	PortalSessionPurposeSetup                       PortalSessionPurpose = "setup"
)

// Defines values for PortalSessionRequestPurpose.
const (
	PortalSessionRequestPurposeCommercialProfileManagement PortalSessionRequestPurpose = "commercial_profile_management"
	PortalSessionRequestPurposeGeneral                     PortalSessionRequestPurpose = "general"
	PortalSessionRequestPurposeInvoiceSelfService          PortalSessionRequestPurpose = "invoice_self_service"
	PortalSessionRequestPurposePaymentMethodManagement     PortalSessionRequestPurpose = "payment_method_management"
	PortalSessionRequestPurposeSetup                       PortalSessionRequestPurpose = "setup"
)

// Account defines model for Account.
type Account struct {
	// BillingCustomerID Current billing customer assigned to this workspace/account. Signup and default workspace creation automatically associate a dormant billing customer/payment profile.
	BillingCustomerID *string `json:"billing_customer_id" yaml:"billing_customer_id"`

	// BillingCustomerReadiness Billing readiness status. Payment-based readiness is established only after a verified commerce-provider/MoR event or server-side provider lookup confirms a saved reusable payment method. Browser redirects alone must not mark a customer billing-ready.
	BillingCustomerReadiness *BillingReadiness `json:"billing_customer_readiness,omitempty" yaml:"billing_customer_readiness,omitempty"`

	// Description description of the account
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Name name of the account
	Name string `json:"name" yaml:"name"`

	// RetentionTier Retention tier for logs/traces (non-numeric label)
	RetentionTier *AccountRetentionTier `json:"retention_tier,omitempty" yaml:"retention_tier,omitempty"`
}

// AccountRetentionTier Retention tier for logs/traces (non-numeric label)
type AccountRetentionTier string

// AccountBody information for a new databacker account
type AccountBody struct {
	// Description description of the account
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// Name name of the account
	Name string `json:"name" yaml:"name"`

	// RetentionTier Retention tier for logs/traces (non-numeric label)
	RetentionTier *AccountBodyRetentionTier `json:"retention_tier,omitempty" yaml:"retention_tier,omitempty"`
}

// AccountBodyRetentionTier Retention tier for logs/traces (non-numeric label)
type AccountBodyRetentionTier string

// AccountMember defines model for AccountMember.
type AccountMember struct {
	// Role role of the user in the account
	Role AccountMemberRole `json:"role" yaml:"role"`

	// User unique ID of the user
	User string `json:"user" yaml:"user"`
}

// AccountMemberRole role of the user in the account
type AccountMemberRole string

// BackupEvent Backup run metadata. Product timeline events are only included when requested with include=events.
type BackupEvent struct {
	// AccountID ID of the account the backup belongs to
	AccountID string `json:"account_id" yaml:"account_id"`

	// Bytes total bytes processed for the backup
	Bytes *int `json:"bytes,omitempty" yaml:"bytes,omitempty"`

	// Completion completion code, using a subset of http codes
	Completion *int `json:"completion,omitempty" yaml:"completion,omitempty"`

	// DatabaseID ID of the database used for the backup
	DatabaseID string `json:"database_id" yaml:"database_id"`

	// DatabaseName display name of the database at the time of the backup
	DatabaseName *string `json:"database_name" yaml:"database_name"`

	// DBSystem Snapshot of the database engine used by the backup
	DBSystem *string `json:"db_system" yaml:"db_system"`

	// DurationMs total duration of the backup in milliseconds
	DurationMs *int `json:"duration_ms,omitempty" yaml:"duration_ms,omitempty"`

	// EndTime timestamp for when the backup completed or failed
	EndTime *time.Time `json:"end_time,omitempty" yaml:"end_time,omitempty"`

	// EngineID ID of the backup engine that performed the backup
	EngineID string `json:"engine_id" yaml:"engine_id"`

	// EngineName display name of the backup engine at the time of the backup
	EngineName *string `json:"engine_name,omitempty" yaml:"engine_name,omitempty"`

	// ErrorMessage error summary when the backup does not succeed
	ErrorMessage *string `json:"error_message,omitempty" yaml:"error_message,omitempty"`

	// Events Chronological product-level timeline events. Only present when backup detail is requested with include=events.
	Events *[]BackupTimelineEvent `json:"events,omitempty" yaml:"events,omitempty"`

	// ID unique backup run identifier
	ID string `json:"id" yaml:"id"`

	// LogID ID of the associated backup log, if available
	LogID *string `json:"log_id,omitempty" yaml:"log_id,omitempty"`

	// NetworkTransport Snapshot of the transport used by the backup
	NetworkTransport *string `json:"network_transport" yaml:"network_transport"`

	// ServerAddress Snapshot of the server hostname, IP, or socket path used by the backup
	ServerAddress *string `json:"server_address" yaml:"server_address"`

	// ServerPort Snapshot of the server port used by the backup, if applicable
	ServerPort *int `json:"server_port" yaml:"server_port"`

	// StartTime timestamp for when the backup started
	StartTime time.Time `json:"start_time" yaml:"start_time"`

	// Status backup result status, such as success or failure
	Status string `json:"status" yaml:"status"`

	// TraceID ID of the associated backup trace, if available
	TraceID *string `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// BackupTimelineEvent Product-level backup timeline event derived from telemetry when available.
type BackupTimelineEvent struct {
	// Attributes Product-safe key/value details, not necessarily the full raw OTEL payload
	Attributes *map[string]interface{} `json:"attributes,omitempty" yaml:"attributes,omitempty"`

	// DurationMs Event duration in milliseconds, if available
	DurationMs *float32 `json:"duration_ms,omitempty" yaml:"duration_ms,omitempty"`

	// ID Optional stable event identifier
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Label Human-readable event label
	Label string `json:"label" yaml:"label"`

	// Message Human-readable event message
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// ParentSpanID Source parent span ID, if derived from a trace span
	ParentSpanID *string `json:"parent_span_id" yaml:"parent_span_id"`

	// Phase Product phase for the event
	Phase string `json:"phase" yaml:"phase"`

	// SpanID Source span ID, if derived from a trace span
	SpanID *string `json:"span_id,omitempty" yaml:"span_id,omitempty"`

	// Status Product-normalized status
	Status *string `json:"status,omitempty" yaml:"status,omitempty"`

	// Time Event timestamp
	Time time.Time `json:"time" yaml:"time"`

	// TraceID Source trace ID, if derived from a trace span
	TraceID *string `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// BackupTimelineEvents Chronological product-level events for one backup run.
type BackupTimelineEvents struct {
	// AccountID ID of the account the backup belongs to
	AccountID string `json:"account_id" yaml:"account_id"`

	// BackupID ID of the backup run
	BackupID string `json:"backup_id" yaml:"backup_id"`

	// DatabaseID ID of the protected database, if available
	DatabaseID *string `json:"database_id" yaml:"database_id"`

	// EngineID ID of the backup engine, if available
	EngineID *string               `json:"engine_id" yaml:"engine_id"`
	Events   []BackupTimelineEvent `json:"events" yaml:"events"`

	// TraceID Primary trace ID used to derive events, if available
	TraceID *string `json:"trace_id" yaml:"trace_id"`
}

// BackupTraceDiagnostics Raw trace diagnostics for one backup run. Product UIs should use backup timeline events for normal status timelines.
type BackupTraceDiagnostics struct {
	// AccountID ID of the account the backup belongs to
	AccountID string `json:"account_id" yaml:"account_id"`

	// BackupID ID of the backup run
	BackupID string `json:"backup_id" yaml:"backup_id"`

	// DatabaseID ID of the protected database, if available
	DatabaseID *string `json:"database_id" yaml:"database_id"`

	// EngineID ID of the backup engine, if available
	EngineID *string `json:"engine_id" yaml:"engine_id"`
	Traces   []Trace `json:"traces" yaml:"traces"`
}

// BillingCatalog defines model for BillingCatalog.
type BillingCatalog struct {
	GeneratedAt *time.Time       `json:"generated_at" yaml:"generated_at"`
	Products    []BillingProduct `json:"products" yaml:"products"`
}

// BillingChargeLine defines model for BillingChargeLine.
type BillingChargeLine struct {
	AccountID         string    `json:"account_id" yaml:"account_id"`
	AmountCents       int       `json:"amount_cents" yaml:"amount_cents"`
	BillingCustomerID string    `json:"billing_customer_id" yaml:"billing_customer_id"`
	Currency          string    `json:"currency" yaml:"currency"`
	DatabaseID        *string   `json:"database_id" yaml:"database_id"`
	IntervalEnd       time.Time `json:"interval_end" yaml:"interval_end"`
	IntervalStart     time.Time `json:"interval_start" yaml:"interval_start"`
	PriceID           string    `json:"price_id" yaml:"price_id"`
	PriceVersion      string    `json:"price_version" yaml:"price_version"`
	ProductID         string    `json:"product_id" yaml:"product_id"`

	// Quantity Interval-adjusted quantity for the monthly charge period.
	Quantity float32 `json:"quantity" yaml:"quantity"`
}

// BillingCustomer defines model for BillingCustomer.
type BillingCustomer struct {
	// Accounts Workspaces/accounts currently visible to the caller for this payer.
	Accounts  *[]BillingCustomerAccountAssociation `json:"accounts,omitempty" yaml:"accounts,omitempty"`
	CreatedAt *time.Time                           `json:"created_at" yaml:"created_at"`

	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// PaymentMethod Provider/MoR-managed payment method display status. Raw payment credentials are never exposed or accepted by this API.
	PaymentMethod *PaymentMethodDisplay `json:"payment_method,omitempty" yaml:"payment_method,omitempty"`

	// Profile Non-sensitive Databacker-owned payer metadata. Updating this profile does not create payment readiness and never submits raw card, bank, or other payment credentials.
	Profile *BillingCustomerProfile `json:"profile,omitempty" yaml:"profile,omitempty"`

	// Readiness Billing readiness status. Payment-based readiness is established only after a verified commerce-provider/MoR event or server-side provider lookup confirms a saved reusable payment method. Browser redirects alone must not mark a customer billing-ready.
	Readiness *BillingReadiness `json:"readiness,omitempty" yaml:"readiness,omitempty"`
	UpdatedAt *time.Time        `json:"updated_at" yaml:"updated_at"`
}

// BillingCustomerAccountAssociation defines model for BillingCustomerAccountAssociation.
type BillingCustomerAccountAssociation struct {
	AccountID    string     `json:"account_id" yaml:"account_id"`
	AccountName  *string    `json:"account_name" yaml:"account_name"`
	AssociatedAt *time.Time `json:"associated_at" yaml:"associated_at"`

	// Current Whether this billing customer is currently assigned to the account.
	Current bool `json:"current" yaml:"current"`
}

// BillingCustomerBody Request to create an additional billing customer/payment profile. Signup and default account creation automatically create a dormant billing customer association, so users do not need this before exploring the product.
type BillingCustomerBody struct {
	// AccountID Optional account to associate with the new billing customer when permitted. Workspace reassignment between existing billing customers is out of scope for this contract.
	AccountID *string `json:"account_id" yaml:"account_id"`

	// Profile Non-sensitive Databacker-owned payer metadata. Updating this profile does not create payment readiness and never submits raw card, bank, or other payment credentials.
	Profile BillingCustomerProfile `json:"profile" yaml:"profile"`
}

// BillingCustomerProfile Non-sensitive Databacker-owned payer metadata. Updating this profile does not create payment readiness and never submits raw card, bank, or other payment credentials.
type BillingCustomerProfile struct {
	AddressLine1 *string `json:"address_line1" yaml:"address_line1"`
	AddressLine2 *string `json:"address_line2" yaml:"address_line2"`
	City         *string `json:"city" yaml:"city"`
	Company      *string `json:"company" yaml:"company"`

	// Country ISO 3166 country code when known.
	Country *string `json:"country" yaml:"country"`

	// Email Billing contact email.
	Email *openapi_types.Email `json:"email" yaml:"email"`

	// Name Display name for the payer profile.
	Name       string  `json:"name" yaml:"name"`
	PostalCode *string `json:"postal_code" yaml:"postal_code"`
	Region     *string `json:"region" yaml:"region"`

	// TaxIDDisplay Non-sensitive tax identifier display label, if available from Databacker-owned metadata.
	TaxIDDisplay *string `json:"tax_id_display" yaml:"tax_id_display"`
}

// BillingEntitlement Auditable billable entitlement interval for one protected database. Historical billed-customer attribution must not be rewritten if a workspace is later assigned to another billing customer.
type BillingEntitlement struct {
	// AccountID Workspace/account consuming the protected database entitlement.
	AccountID        string                             `json:"account_id" yaml:"account_id"`
	ActivationReason BillingEntitlementActivationReason `json:"activation_reason" yaml:"activation_reason"`
	Active           bool                               `json:"active" yaml:"active"`

	// BillingCustomerID Payer attributed to this interval.
	BillingCustomerID string `json:"billing_customer_id" yaml:"billing_customer_id"`

	// DatabaseID Protected database resource identity.
	DatabaseID string `json:"database_id" yaml:"database_id"`

	// DatabaseStableIdentity Engine-reported stable identity captured for audit.
	DatabaseStableIdentity *string                               `json:"database_stable_identity" yaml:"database_stable_identity"`
	DeactivationReason     *BillingEntitlementDeactivationReason `json:"deactivation_reason" yaml:"deactivation_reason"`
	EndedAt                *time.Time                            `json:"ended_at" yaml:"ended_at"`
	ID                     string                                `json:"id" yaml:"id"`
	PriceID                string                                `json:"price_id" yaml:"price_id"`
	PriceVersion           string                                `json:"price_version" yaml:"price_version"`
	ProductID              string                                `json:"product_id" yaml:"product_id"`
	StartedAt              time.Time                             `json:"started_at" yaml:"started_at"`
}

// BillingEntitlementActivationReason defines model for BillingEntitlement.ActivationReason.
type BillingEntitlementActivationReason string

// BillingEntitlementDeactivationReason defines model for BillingEntitlement.DeactivationReason.
type BillingEntitlementDeactivationReason string

// BillingEstimate Estimated charges calculated from entitlement intervals for the requested period.
type BillingEstimate struct {
	AccountID         *string             `json:"account_id" yaml:"account_id"`
	BillingCustomerID *string             `json:"billing_customer_id" yaml:"billing_customer_id"`
	Currency          string              `json:"currency" yaml:"currency"`
	Lines             []BillingChargeLine `json:"lines" yaml:"lines"`
	PeriodEnd         time.Time           `json:"period_end" yaml:"period_end"`
	PeriodStart       time.Time           `json:"period_start" yaml:"period_start"`
	TotalAmountCents  int                 `json:"total_amount_cents" yaml:"total_amount_cents"`
}

// BillingPrice defines model for BillingPrice.
type BillingPrice struct {
	// Currency ISO 4217 currency code.
	Currency       string               `json:"currency" yaml:"currency"`
	EffectiveFrom  *time.Time           `json:"effective_from" yaml:"effective_from"`
	EffectiveUntil *time.Time           `json:"effective_until" yaml:"effective_until"`
	Interval       BillingPriceInterval `json:"interval" yaml:"interval"`
	PriceID        string               `json:"price_id" yaml:"price_id"`

	// UnitAmountCents Monthly unit price in minor currency units for one active protected database before interval proration.
	UnitAmountCents int    `json:"unit_amount_cents" yaml:"unit_amount_cents"`
	Version         string `json:"version" yaml:"version"`
}

// BillingPriceInterval defines model for BillingPrice.Interval.
type BillingPriceInterval string

// BillingProduct defines model for BillingProduct.
type BillingProduct struct {
	// BillableUnit The base billable product is an active protected database.
	BillableUnit BillingProductBillableUnit `json:"billable_unit" yaml:"billable_unit"`
	Name         string                     `json:"name" yaml:"name"`
	Prices       []BillingPrice             `json:"prices" yaml:"prices"`

	// ProductID Stable product identifier.
	ProductID string `json:"product_id" yaml:"product_id"`
}

// BillingProductBillableUnit The base billable product is an active protected database.
type BillingProductBillableUnit string

// BillingReadiness Billing readiness status. Payment-based readiness is established only after a verified commerce-provider/MoR event or server-side provider lookup confirms a saved reusable payment method. Browser redirects alone must not mark a customer billing-ready.
type BillingReadiness struct {
	ConfirmedAt *time.Time `json:"confirmed_at" yaml:"confirmed_at"`

	// ReadyForPaidActivation True only when new paid database activation or reactivation is allowed.
	ReadyForPaidActivation bool                    `json:"ready_for_paid_activation" yaml:"ready_for_paid_activation"`
	Reason                 *BillingReadinessReason `json:"reason" yaml:"reason"`
	State                  BillingReadinessState   `json:"state" yaml:"state"`
}

// BillingReadinessReason defines model for BillingReadiness.Reason.
type BillingReadinessReason string

// BillingReadinessState defines model for BillingReadiness.State.
type BillingReadinessState string

// BillingSummary Billing summary for either a payer or one workspace. Amounts vary by active entitlement intervals; backup attempts, logs, traces, failures, and health do not directly determine base billing.
type BillingSummary struct {
	AccountID                    *string `json:"account_id" yaml:"account_id"`
	ActiveProtectedDatabaseCount int     `json:"active_protected_database_count" yaml:"active_protected_database_count"`
	BillingCustomerID            *string `json:"billing_customer_id" yaml:"billing_customer_id"`
	Currency                     string  `json:"currency" yaml:"currency"`
	CurrentMonthAmountCents      int     `json:"current_month_amount_cents" yaml:"current_month_amount_cents"`
	OpenEntitlementCount         int     `json:"open_entitlement_count" yaml:"open_entitlement_count"`

	// Readiness Billing readiness status. Payment-based readiness is established only after a verified commerce-provider/MoR event or server-side provider lookup confirms a saved reusable payment method. Browser redirects alone must not mark a customer billing-ready.
	Readiness *BillingReadiness `json:"readiness,omitempty" yaml:"readiness,omitempty"`
}

// Database defines model for Database.
type Database struct {
	// AccountID ID of the account that owns the database
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// Address Hostname or IP address for TCP, or socket path for unix transport
	Address string `json:"address" yaml:"address"`

	// AutomaticDiscoveryChargeAcknowledged When true during engine setup or accepted discovery enrollment, the account administrator has acknowledged that newly discovered protected databases may activate and incur charges only when the assigned billing customer is billing-ready.
	AutomaticDiscoveryChargeAcknowledged *bool `json:"automatic_discovery_charge_acknowledged" yaml:"automatic_discovery_charge_acknowledged"`

	// CreatedAt Timestamp when the database was created
	CreatedAt *time.Time `json:"created_at" yaml:"created_at"`

	// DisplayName Deprecated alias for name retained only for existing stored metadata readers
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	DisplayName *string `json:"display_name" yaml:"display_name"`

	// EngineID ID of the backup engine that protects this database
	EngineID string `json:"engine_id" yaml:"engine_id"`

	// EngineName display name of the backup engine protecting this database
	EngineName *string `json:"engine_name" yaml:"engine_name"`

	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// LastFailedBackup timestamp of the latest failed backup for this database
	LastFailedBackup *time.Time `json:"last_failed_backup" yaml:"last_failed_backup"`

	// LastSuccessfulBackup timestamp of the latest successful backup for this database
	LastSuccessfulBackup *time.Time `json:"last_successful_backup" yaml:"last_successful_backup"`

	// LatestBackupStatus status of the latest backup for this database
	LatestBackupStatus *string `json:"latest_backup_status" yaml:"latest_backup_status"`

	// LatestErrorMessage error message from the latest failed backup, if available
	LatestErrorMessage *string `json:"latest_error_message" yaml:"latest_error_message"`

	// Name Human-friendly display name for the database
	Name string `json:"name" yaml:"name"`

	// Port TCP port for the database target, if applicable
	Port *int `json:"port" yaml:"port"`

	// ProtectionLifecycle Billable protection lifecycle for a database. This state is separate from operational health, backup success, failures, logs, and traces.
	ProtectionLifecycle *DatabaseProtectionLifecycle `json:"protection_lifecycle,omitempty" yaml:"protection_lifecycle,omitempty"`

	// StableIdentity Stable engine-reported database identity used to match discovery reports across display-name or endpoint changes. Names and endpoints alone are not sufficient for enrollment, blocked rediscovery, or reactivation evidence.
	StableIdentity *string `json:"stable_identity" yaml:"stable_identity"`

	// System Database engine type
	System string `json:"system" yaml:"system"`

	// Transport Network transport used to reach the database target
	Transport string `json:"transport" yaml:"transport"`

	// UpdatedAt Timestamp when the database was last updated
	UpdatedAt *time.Time `json:"updated_at" yaml:"updated_at"`
}

// DatabaseBody A protected database endpoint or socket used as a backup source.
type DatabaseBody struct {
	// Address Hostname or IP address for TCP, or socket path for unix transport
	Address string `json:"address" yaml:"address"`

	// AutomaticDiscoveryChargeAcknowledged When true during engine setup or accepted discovery enrollment, the account administrator has acknowledged that newly discovered protected databases may activate and incur charges only when the assigned billing customer is billing-ready.
	AutomaticDiscoveryChargeAcknowledged *bool `json:"automatic_discovery_charge_acknowledged" yaml:"automatic_discovery_charge_acknowledged"`

	// DisplayName Deprecated alias for name retained only for existing stored metadata readers
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	DisplayName *string `json:"display_name" yaml:"display_name"`

	// EngineID ID of the backup engine that protects this database
	EngineID string `json:"engine_id" yaml:"engine_id"`

	// Name Human-friendly display name for the database
	Name string `json:"name" yaml:"name"`

	// Port TCP port for the database target, if applicable
	Port *int `json:"port" yaml:"port"`

	// StableIdentity Stable engine-reported database identity used to match discovery reports across display-name or endpoint changes. Names and endpoints alone are not sufficient for enrollment, blocked rediscovery, or reactivation evidence.
	StableIdentity *string `json:"stable_identity" yaml:"stable_identity"`

	// System Database engine type
	System string `json:"system" yaml:"system"`

	// Transport Network transport used to reach the database target
	Transport string `json:"transport" yaml:"transport"`
}

// DatabaseDeactivationRequest defines model for DatabaseDeactivationRequest.
type DatabaseDeactivationRequest struct {
	// Reason Optional user-supplied deactivation reason or note.
	Reason *string `json:"reason" yaml:"reason"`
}

// DatabaseLifecycleActionRequest defines model for DatabaseLifecycleActionRequest.
type DatabaseLifecycleActionRequest struct {
	// ChargeAcknowledged Must be true for paid activation or reactivation actions that can open a billing entitlement and incur charges.
	ChargeAcknowledged bool `json:"charge_acknowledged" yaml:"charge_acknowledged"`

	// Reason Optional user-supplied lifecycle reason or note.
	Reason *string `json:"reason" yaml:"reason"`
}

// DatabaseProtectionLifecycle Billable protection lifecycle for a database. This state is separate from operational health, backup success, failures, logs, and traces.
type DatabaseProtectionLifecycle struct {
	// ActivatedAt Timestamp when the current active protection interval opened.
	ActivatedAt *time.Time `json:"activated_at" yaml:"activated_at"`

	// ActivationReason Reason the current active interval opened.
	ActivationReason *DatabaseProtectionLifecycleActivationReason `json:"activation_reason" yaml:"activation_reason"`

	// CurrentEntitlementID Active billing entitlement interval ID, if protection is active.
	CurrentEntitlementID *string `json:"current_entitlement_id" yaml:"current_entitlement_id"`

	// DeactivatedAt Timestamp when protection was explicitly deactivated.
	DeactivatedAt *time.Time `json:"deactivated_at" yaml:"deactivated_at"`

	// DeactivationReason Reason protection was explicitly deactivated.
	DeactivationReason *DatabaseProtectionLifecycleDeactivationReason `json:"deactivation_reason" yaml:"deactivation_reason"`

	// PendingReactivation Summary of reports retained after explicit deactivation. Reports for a deactivated database must not silently reactivate or bill the database.
	PendingReactivation *PendingReactivationSummary `json:"pending_reactivation,omitempty" yaml:"pending_reactivation,omitempty"`

	// State Current billable protection state. Active databases remain billable until explicitly deactivated.
	State DatabaseProtectionLifecycleState `json:"state" yaml:"state"`
}

// DatabaseProtectionLifecycleActivationReason Reason the current active interval opened.
type DatabaseProtectionLifecycleActivationReason string

// DatabaseProtectionLifecycleDeactivationReason Reason protection was explicitly deactivated.
type DatabaseProtectionLifecycleDeactivationReason string

// DatabaseProtectionLifecycleState Current billable protection state. Active databases remain billable until explicitly deactivated.
type DatabaseProtectionLifecycleState string

// DatabaseSummary protected database row summary for list views
type DatabaseSummary struct {
	// AccountID ID of the account that owns the database
	AccountID string `json:"account_id" yaml:"account_id"`

	// CreatedAt Timestamp when the database target was created
	CreatedAt *time.Time `json:"created_at" yaml:"created_at"`

	// EngineID ID of the backup engine that protects this database
	EngineID string `json:"engine_id" yaml:"engine_id"`

	// EngineName display name of the backup engine protecting this database
	EngineName *string `json:"engine_name" yaml:"engine_name"`

	// ID Unique identifier of the database
	ID string `json:"id" yaml:"id"`

	// LastFailedBackup timestamp of the latest failed backup for this database
	LastFailedBackup *time.Time `json:"last_failed_backup" yaml:"last_failed_backup"`

	// LastSuccessfulBackup timestamp of the latest successful backup for this database
	LastSuccessfulBackup *time.Time `json:"last_successful_backup" yaml:"last_successful_backup"`

	// LatestBackupStatus status of the latest backup for this database
	LatestBackupStatus *string `json:"latest_backup_status" yaml:"latest_backup_status"`

	// LatestErrorMessage error message from the latest failed backup, if available
	LatestErrorMessage *string `json:"latest_error_message" yaml:"latest_error_message"`

	// Name Human-friendly display name for the database
	Name string `json:"name" yaml:"name"`

	// ProtectionLifecycle Billable protection lifecycle for a database. This state is separate from operational health, backup success, failures, logs, and traces.
	ProtectionLifecycle *DatabaseProtectionLifecycle `json:"protection_lifecycle,omitempty" yaml:"protection_lifecycle,omitempty"`

	// System Database engine type
	System string `json:"system" yaml:"system"`

	// UpdatedAt Timestamp when the database target was last updated
	UpdatedAt *time.Time `json:"updated_at" yaml:"updated_at"`
}

// Email defines model for Email.
type Email struct {
	// Email email address of the user
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`
}

// EmailChangePending defines model for EmailChangePending.
type EmailChangePending struct {
	Email     openapi_types.Email      `json:"email" yaml:"email"`
	ExpiresAt time.Time                `json:"expires_at" yaml:"expires_at"`
	Status    EmailChangePendingStatus `json:"status" yaml:"status"`
}

// EmailChangePendingStatus defines model for EmailChangePending.Status.
type EmailChangePendingStatus string

// Engine defines model for Engine.
type Engine struct {
	// AccountID ID of the account that owns the backup engine
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// AutomaticDiscoveryChargeAcknowledged Engine setup acknowledgement that newly discovered protected databases may automatically activate and incur charges only when the workspace's assigned billing customer is billing-ready. This does not override billing readiness requirements.
	AutomaticDiscoveryChargeAcknowledged *bool `json:"automatic_discovery_charge_acknowledged" yaml:"automatic_discovery_charge_acknowledged"`

	// ConfigState computed configuration state for the backup engine
	ConfigState *EngineConfigState `json:"config_state,omitempty" yaml:"config_state,omitempty"`

	// CreatedAt timestamp when the backup engine was created
	CreatedAt *time.Time `json:"created_at" yaml:"created_at"`

	// Description description of the backup engine
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// LastSeen timestamp of the latest heartbeat or authenticated request
	LastSeen *time.Time `json:"last_seen" yaml:"last_seen"`

	// Name name of the backup engine
	Name string `json:"name" yaml:"name"`

	// PublicKey ECDSA public key to associate with the backup engine, PEM-encoded
	PublicKey *string `json:"publicKey,omitempty" yaml:"publicKey,omitempty"`

	// RegistrationState registration state for the backup engine
	RegistrationState *EngineRegistrationState `json:"registration_state,omitempty" yaml:"registration_state,omitempty"`

	// UpdatedAt timestamp when the backup engine was last updated
	UpdatedAt *time.Time `json:"updated_at" yaml:"updated_at"`

	// Version backup engine software version, if reported
	Version *string `json:"version" yaml:"version"`
}

// EngineConfigState computed configuration state for the backup engine
type EngineConfigState string

// EngineRegistrationState registration state for the backup engine
type EngineRegistrationState string

// EngineBody information for a backup engine registration
type EngineBody struct {
	// AutomaticDiscoveryChargeAcknowledged Engine setup acknowledgement that newly discovered protected databases may automatically activate and incur charges only when the workspace's assigned billing customer is billing-ready. This does not override billing readiness requirements.
	AutomaticDiscoveryChargeAcknowledged *bool `json:"automatic_discovery_charge_acknowledged" yaml:"automatic_discovery_charge_acknowledged"`

	// Description description of the backup engine
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// Name name of the backup engine
	Name string `json:"name" yaml:"name"`

	// PublicKey ECDSA public key to associate with the backup engine, PEM-encoded
	PublicKey *string `json:"publicKey,omitempty" yaml:"publicKey,omitempty"`
}

// EngineSummary backup engine row summary for list views
type EngineSummary struct {
	// AccountID ID of the account that owns the backup engine
	AccountID   string                   `json:"account_id" yaml:"account_id"`
	ConfigState EngineSummaryConfigState `json:"config_state" yaml:"config_state"`

	// ConnectedDatabaseID database ID when this engine is currently associated with one database
	ConnectedDatabaseID *string `json:"connected_database_id" yaml:"connected_database_id"`

	// ConnectedDatabaseName database display name when this engine is currently associated with one database
	ConnectedDatabaseName *string `json:"connected_database_name" yaml:"connected_database_name"`

	// DatabaseCount number of databases protected by this backup engine
	DatabaseCount int `json:"database_count" yaml:"database_count"`

	// Description description of the backup engine
	Description *string `json:"description" yaml:"description"`

	// ID Unique identifier of the backup engine
	ID                   string     `json:"id" yaml:"id"`
	LastFailedBackup     *time.Time `json:"last_failed_backup" yaml:"last_failed_backup"`
	LastSeen             *time.Time `json:"last_seen" yaml:"last_seen"`
	LastSuccessfulBackup *time.Time `json:"last_successful_backup" yaml:"last_successful_backup"`

	// LatestBackupStatus status of the latest backup across databases protected by this engine
	LatestBackupStatus *string `json:"latest_backup_status" yaml:"latest_backup_status"`

	// Name name of the backup engine
	Name              string                         `json:"name" yaml:"name"`
	RegistrationState EngineSummaryRegistrationState `json:"registration_state" yaml:"registration_state"`
	Version           *string                        `json:"version" yaml:"version"`
}

// EngineSummaryConfigState defines model for EngineSummary.ConfigState.
type EngineSummaryConfigState string

// EngineSummaryRegistrationState defines model for EngineSummary.RegistrationState.
type EngineSummaryRegistrationState string

// FlatTrace defines model for FlatTrace.
type FlatTrace struct {
	// AccountID ID of the account the database belongs to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// DatabaseID ID of the database the trace belongs to
	DatabaseID *string `json:"database_id,omitempty" yaml:"database_id,omitempty"`

	// EngineID ID of the backup engine that produced the trace
	EngineID *string     `json:"engine_id" yaml:"engine_id"`
	Spans    *[]SpanFlat `json:"spans,omitempty" yaml:"spans,omitempty"`
	TraceID  *string     `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// ID defines model for ID.
type ID struct {
	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`
}

// InvoiceArtifact Single finalized invoice artifact. The artifact may be PDF, HTML, or a commerce-provider/MoR-backed redirect depending on provider capabilities.
type InvoiceArtifact struct {
	ArtifactType InvoiceArtifactArtifactType `json:"artifact_type" yaml:"artifact_type"`
	ContentType  *string                     `json:"content_type" yaml:"content_type"`
	ExpiresAt    *time.Time                  `json:"expires_at" yaml:"expires_at"`

	// HTML Inline HTML artifact when the provider and implementation support it.
	HTML *string `json:"html" yaml:"html"`

	// Invoice Finalized invoice known for a billing customer.
	Invoice InvoiceSummary `json:"invoice" yaml:"invoice"`

	// URL Provider/MoR-backed artifact redirect or signed download URL.
	URL *string `json:"url" yaml:"url"`
}

// InvoiceArtifactArtifactType defines model for InvoiceArtifact.ArtifactType.
type InvoiceArtifactArtifactType string

// InvoiceSummary Finalized invoice known for a billing customer.
type InvoiceSummary struct {
	AmountDueCents    int                  `json:"amount_due_cents" yaml:"amount_due_cents"`
	AmountPaidCents   *int                 `json:"amount_paid_cents,omitempty" yaml:"amount_paid_cents,omitempty"`
	BillingCustomerID string               `json:"billing_customer_id" yaml:"billing_customer_id"`
	Currency          string               `json:"currency" yaml:"currency"`
	ID                string               `json:"id" yaml:"id"`
	IssuedAt          time.Time            `json:"issued_at" yaml:"issued_at"`
	PeriodEnd         *time.Time           `json:"period_end,omitempty" yaml:"period_end,omitempty"`
	PeriodStart       *time.Time           `json:"period_start,omitempty" yaml:"period_start,omitempty"`
	ProviderInvoiceID *string              `json:"provider_invoice_id" yaml:"provider_invoice_id"`
	Status            InvoiceSummaryStatus `json:"status" yaml:"status"`
}

// InvoiceSummaryStatus defines model for InvoiceSummary.Status.
type InvoiceSummaryStatus string

// Log defines model for Log.
type Log struct {
	// AccountID ID of the account the logs belong to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// DatabaseID ID of the database the logs belong to
	DatabaseID *string `json:"database_id,omitempty" yaml:"database_id,omitempty"`

	// EngineID ID of the backup engine that produced the logs
	EngineID *string `json:"engine_id" yaml:"engine_id"`

	// Lines List of log lines for a backup run
	Lines *[]LogLine `json:"lines,omitempty" yaml:"lines,omitempty"`
}

// LogLine defines model for LogLine.
type LogLine struct {
	// Fields key-value pairs for descriptive fields for the log message
	Fields *map[string]interface{} `json:"fields,omitempty" yaml:"fields,omitempty"`

	// Level log level of the message, one of debug, info, warn, error, fatal
	Level *string `json:"level,omitempty" yaml:"level,omitempty"`

	// Message actual message
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`

	// Run run ID as UUID
	Run *string `json:"run,omitempty" yaml:"run,omitempty"`

	// Timestamp timestamp for the date and time of a message, in RFC3339 format
	Timestamp *string `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
}

// LogSummary defines model for LogSummary.
type LogSummary struct {
	// AccountID ID of the account the logs belong to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// Completion completion code, using a subset of http codes
	Completion *int `json:"completion,omitempty" yaml:"completion,omitempty"`

	// DatabaseID ID of the database the logs belong to
	DatabaseID *string `json:"database_id,omitempty" yaml:"database_id,omitempty"`

	// Date timestamp for start of backup run
	Date *int `json:"date,omitempty" yaml:"date,omitempty"`

	// EngineID ID of the backup engine that produced the logs
	EngineID *string `json:"engine_id" yaml:"engine_id"`
	ID       *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Size size of logs in bytes
	Size *int `json:"size,omitempty" yaml:"size,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	// Description description of the config
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`

	// Digest SHA256 digest of the config, optional
	Digest *string `json:"digest,omitempty" yaml:"digest,omitempty"`

	// Name name of the config
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

// PaginatedAccountMembers defines model for PaginatedAccountMembers.
type PaginatedAccountMembers struct {
	HasNext *bool            `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool            `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int             `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *int             `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int             `json:"total,omitempty" yaml:"total,omitempty"`
	Users   *[]AccountMember `json:"users,omitempty" yaml:"users,omitempty"`
}

// PaginatedAccounts defines model for PaginatedAccounts.
type PaginatedAccounts struct {
	Accounts *[]Account `json:"accounts,omitempty" yaml:"accounts,omitempty"`
	HasNext  *bool      `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev  *bool      `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit    *int       `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset   *int       `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total    *int       `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedBackupEvents defines model for PaginatedBackupEvents.
type PaginatedBackupEvents struct {
	// Events Paginated backup run summaries. List endpoints must not embed product timeline events.
	Events  *[]BackupEvent `json:"events,omitempty" yaml:"events,omitempty"`
	HasNext *bool          `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool          `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int           `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *int           `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int           `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedBillingCustomers defines model for PaginatedBillingCustomers.
type PaginatedBillingCustomers struct {
	BillingCustomers *[]BillingCustomer `json:"billing_customers,omitempty" yaml:"billing_customers,omitempty"`
	HasNext          *bool              `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev          *bool              `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit            *int               `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset           *int               `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total            *int               `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedBillingEntitlements defines model for PaginatedBillingEntitlements.
type PaginatedBillingEntitlements struct {
	Entitlements *[]BillingEntitlement `json:"entitlements,omitempty" yaml:"entitlements,omitempty"`
	HasNext      *bool                 `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev      *bool                 `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit        *int                  `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset       *int                  `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total        *int                  `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedDatabases defines model for PaginatedDatabases.
type PaginatedDatabases struct {
	Databases *[]DatabaseSummary `json:"databases,omitempty" yaml:"databases,omitempty"`
	HasNext   *bool              `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev   *bool              `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit     *int               `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset    *int               `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total     *int               `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedEngines defines model for PaginatedEngines.
type PaginatedEngines struct {
	Engines *[]EngineSummary `json:"engines,omitempty" yaml:"engines,omitempty"`
	HasNext *bool            `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool            `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int             `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *int             `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int             `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedInvoices defines model for PaginatedInvoices.
type PaginatedInvoices struct {
	HasNext  *bool             `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev  *bool             `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Invoices *[]InvoiceSummary `json:"invoices,omitempty" yaml:"invoices,omitempty"`
	Limit    *int              `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset   *int              `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total    *int              `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedLogSummaries defines model for PaginatedLogSummaries.
type PaginatedLogSummaries struct {
	HasNext *bool         `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool         `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int          `json:"limit,omitempty" yaml:"limit,omitempty"`
	Logs    *[]LogSummary `json:"logs,omitempty" yaml:"logs,omitempty"`
	Offset  *int          `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int          `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedLogs defines model for PaginatedLogs.
type PaginatedLogs struct {
	HasNext *bool  `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool  `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int   `json:"limit,omitempty" yaml:"limit,omitempty"`
	Logs    *[]Log `json:"logs,omitempty" yaml:"logs,omitempty"`
	Offset  *int   `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int   `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedSelfAccounts defines model for PaginatedSelfAccounts.
type PaginatedSelfAccounts struct {
	Accounts *[]SelfAccountEntry `json:"accounts,omitempty" yaml:"accounts,omitempty"`
	HasNext  *bool               `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev  *bool               `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit    *int                `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset   *int                `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total    *int                `json:"total,omitempty" yaml:"total,omitempty"`
}

// PaginatedUsers defines model for PaginatedUsers.
type PaginatedUsers struct {
	HasNext *bool   `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool   `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int    `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *int    `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int    `json:"total,omitempty" yaml:"total,omitempty"`
	Users   *[]User `json:"users,omitempty" yaml:"users,omitempty"`
}

// PaginationMetadata defines model for PaginationMetadata.
type PaginationMetadata struct {
	HasNext *bool `json:"has_next,omitempty" yaml:"has_next,omitempty"`
	HasPrev *bool `json:"has_prev,omitempty" yaml:"has_prev,omitempty"`
	Limit   *int  `json:"limit,omitempty" yaml:"limit,omitempty"`
	Offset  *int  `json:"offset,omitempty" yaml:"offset,omitempty"`
	Total   *int  `json:"total,omitempty" yaml:"total,omitempty"`
}

// PatchAdminSelfRequest defines model for PatchAdminSelfRequest.
type PatchAdminSelfRequest struct {
	Email *openapi_types.Email `json:"email,omitempty" yaml:"email,omitempty"`
	Name  *string              `json:"name,omitempty" yaml:"name,omitempty"`
}

// PaymentMethodDisplay Provider/MoR-managed payment method display status. Raw payment credentials are never exposed or accepted by this API.
type PaymentMethodDisplay struct {
	// DisplayBrand Safe display brand such as card network or payment family.
	DisplayBrand *string `json:"display_brand" yaml:"display_brand"`

	// DisplayLabel Safe masked display label such as last four digits.
	DisplayLabel *string    `json:"display_label" yaml:"display_label"`
	ExpiresAt    *time.Time `json:"expires_at" yaml:"expires_at"`

	// Provider Commerce provider or merchant-of-record identifier when selected.
	Provider   *string                    `json:"provider" yaml:"provider"`
	Status     PaymentMethodDisplayStatus `json:"status" yaml:"status"`
	VerifiedAt *time.Time                 `json:"verified_at" yaml:"verified_at"`
}

// PaymentMethodDisplayStatus defines model for PaymentMethodDisplay.Status.
type PaymentMethodDisplayStatus string

// PendingReactivationSummary Summary of reports retained after explicit deactivation. Reports for a deactivated database must not silently reactivate or bill the database.
type PendingReactivationSummary struct {
	FirstReportedAt *time.Time `json:"first_reported_at" yaml:"first_reported_at"`
	LastReportedAt  *time.Time `json:"last_reported_at" yaml:"last_reported_at"`

	// LatestEngineID Backup engine that most recently reported this deactivated database.
	LatestEngineID *string `json:"latest_engine_id" yaml:"latest_engine_id"`

	// LatestReportStatus Disposition of the latest post-deactivation report.
	LatestReportStatus *PendingReactivationSummaryLatestReportStatus `json:"latest_report_status" yaml:"latest_report_status"`

	// LatestStableIdentity Stable database identity from the most recent retained report.
	LatestStableIdentity *string `json:"latest_stable_identity" yaml:"latest_stable_identity"`

	// RetainedReportCount Number of post-deactivation reports currently retained as reactivation evidence.
	RetainedReportCount *int `json:"retained_report_count,omitempty" yaml:"retained_report_count,omitempty"`

	// RetainedReportLimit Configured maximum retained post-deactivation reports for this database.
	RetainedReportLimit *int `json:"retained_report_limit,omitempty" yaml:"retained_report_limit,omitempty"`
}

// PendingReactivationSummaryLatestReportStatus Disposition of the latest post-deactivation report.
type PendingReactivationSummaryLatestReportStatus string

// PortalSession defines model for PortalSession.
type PortalSession struct {
	// ClientToken Equivalent hosted-session token when the selected commerce provider uses an embedded client session.
	ClientToken *string               `json:"client_token" yaml:"client_token"`
	ExpiresAt   *time.Time            `json:"expires_at" yaml:"expires_at"`
	Provider    *string               `json:"provider" yaml:"provider"`
	Purpose     *PortalSessionPurpose `json:"purpose" yaml:"purpose"`

	// URL Provider/MoR-hosted redirect URL when the selected commerce provider uses redirects.
	URL *string `json:"url" yaml:"url"`
}

// PortalSessionPurpose defines model for PortalSession.Purpose.
type PortalSessionPurpose string

// PortalSessionRequest Request a single commerce-provider/MoR-hosted flow for initial setup, payment-method management, provider commercial profile management, invoice self-service, or a general billing portal. The redirect result is advisory only; billing readiness and invoice synchronization require verified provider confirmation through webhook/callback processing or server-side provider lookup.
type PortalSessionRequest struct {
	Purpose *PortalSessionRequestPurpose `json:"purpose" yaml:"purpose"`

	// ReturnURL Optional frontend URL to return to after the hosted provider/MoR flow.
	ReturnURL *string `json:"return_url" yaml:"return_url"`
}

// PortalSessionRequestPurpose defines model for PortalSessionRequest.Purpose.
type PortalSessionRequestPurpose string

// SelfAccountEntry an account the calling user belongs to, with their role
type SelfAccountEntry struct {
	// ID unique ID of the account
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Name name of the account
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`

	// Role role of the calling user in this account
	Role *string `json:"role,omitempty" yaml:"role,omitempty"`
}

// Span defines model for Span.
type Span struct {
	Attributes    *map[string]interface{} `json:"attributes,omitempty" yaml:"attributes,omitempty"`
	Children      *[]Span                 `json:"children,omitempty" yaml:"children,omitempty"`
	DurationMs    *float32                `json:"duration_ms,omitempty" yaml:"duration_ms,omitempty"`
	EndTime       *time.Time              `json:"end_time,omitempty" yaml:"end_time,omitempty"`
	OperationName *string                 `json:"operation_name,omitempty" yaml:"operation_name,omitempty"`
	ParentSpanID  *string                 `json:"parent_span_id" yaml:"parent_span_id"`

	// Payload Full OpenTelemetry span payload
	Payload   *map[string]interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`
	SpanID    *string                 `json:"span_id,omitempty" yaml:"span_id,omitempty"`
	StartTime *time.Time              `json:"start_time,omitempty" yaml:"start_time,omitempty"`
}

// SpanFlat defines model for SpanFlat.
type SpanFlat struct {
	Attributes    *map[string]interface{} `json:"attributes,omitempty" yaml:"attributes,omitempty"`
	EndTime       *time.Time              `json:"end_time,omitempty" yaml:"end_time,omitempty"`
	OperationName *string                 `json:"operation_name,omitempty" yaml:"operation_name,omitempty"`
	ParentSpanID  *string                 `json:"parent_span_id" yaml:"parent_span_id"`
	Payload       *map[string]interface{} `json:"payload,omitempty" yaml:"payload,omitempty"`
	SpanID        *string                 `json:"span_id,omitempty" yaml:"span_id,omitempty"`
	StartTime     *time.Time              `json:"start_time,omitempty" yaml:"start_time,omitempty"`
}

// Trace Raw trace diagnostic data for a backup run.
type Trace struct {
	// AccountID ID of the account the database belongs to
	AccountID *string `json:"account_id,omitempty" yaml:"account_id,omitempty"`

	// BackupID ID of the backup run this trace belongs to
	BackupID *string `json:"backup_id,omitempty" yaml:"backup_id,omitempty"`

	// DatabaseID ID of the database the trace belongs to
	DatabaseID *string `json:"database_id,omitempty" yaml:"database_id,omitempty"`

	// EngineID ID of the backup engine that produced the trace
	EngineID  *string             `json:"engine_id" yaml:"engine_id"`
	RootSpans *[]Span             `json:"root_spans,omitempty" yaml:"root_spans,omitempty"`
	TraceID   *openapi_types.UUID `json:"trace_id,omitempty" yaml:"trace_id,omitempty"`
}

// User defines model for User.
type User struct {
	// Email email address of the user
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`

	// ID unique ID of the object, as a UUID
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Name full name of the user
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

// UserBody information for a new user
type UserBody struct {
	// Email email address of the user
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`

	// Name full name of the user
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}

// UserWithEmail defines model for UserWithEmail.
type UserWithEmail struct {
	// Email email address of the user
	Email *string `json:"email,omitempty" yaml:"email,omitempty"`

	// Name full name of the user
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
}
